### ISSUE TITLE
Our Abstract Classes Are Not Abstract Classes In Python3!

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#106]
It turns out the syntax to declare metaclass has been changed in Python3. That's why our abstract methods can be called in Python3: they are not abstract in fact!

For more detail see the link below:
http://stackoverflow.com/questions/18513821/python-metaclass-understanding-the-with-metaclass/18513858#18513858

**Comment by bartvm** [comment]
I'll do a few search and replace commands. There seem to be two options in `six`:
```python
@add_metaclass(ABCMeta)
class SomeBrick(Brick):
    pass
```
or
```python
class SomeBrick(with_metaclass(ABCMeta, Brick)):
    pass
```
I prefer the first.

**Comment by rizar** [comment]
I also like the first more.
