### ISSUE TITLE
PyLearn2 Markov Chain Test Is Broken

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#119]
#115 breaks it by changing the way activation classes are serialized.

Perhaps we should just not use class generation? Apart from serialization problems it is quite hard to read for people with limited Python knowledge.

**Comment by bartvm** [comment]
Although I agree that we should use class factories very sparingly, I think that in this case it's quite justified. As we go along, there might be many different tiny Theano operations that we want to wrap as activation functions. In that case would end up with a long file full of copy-pasted class definitions, inluding lengthy docstrings which are all exactly the same.

We can replace the lambda operations with short function definitions though, that could fix the bug. Let me try.

**Comment by rizar** [comment]
But you can attach the docstring by a decorator, can't you? And in general, instead of class factory pattern we could use class modifier pattern:

```python

def activation(class_):
     # add the stuff shared by all activation classes

@activation
class Sigmoid(object):
     # the stuff specific to Sigmoid goes here

```

**Comment by bartvm** [comment]
Well, not with a decorator, but with a metaclass (http://bugs.python.org/issue12773). You're right though, if the factor out the docstring stuff there is almost nothing left. Does this work?

```python
@add_metaclass(ActivationDocumentation)
class Activation(Brick):
    pass

class Sigmoid(Activation):
    @application(inputs=['input_'], outputs=['output'])
    def apply(self, input_):
        return tensor.nnet.sigmoid(input_)
```

**Comment by rizar** [comment]
Looks just perfect for me!

**Comment by bartvm** [comment]
Okay, updated #121; let's just wait for Travis.

**Comment by rizar** [comment]
Broken again after #127.
