### ISSUE TITLE
Safety Check for MNIST Needed

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#122]
We should check the incoming request in `MNIST.get_data`. I spent an hour trying to understand what's going on when I simply passed it wrong indices. The challenge is, that the `request` can be an index, sequence of indices and slice, and all this cases need different code to be handled.

**Comment by bartvm** [comment]
Yeah, I have it as a todo here: https://github.com/bartvm/blocks/blob/master/blocks/datasets/__init__.py#L113-L117

**Comment by rizar** [comment]
Yeah, but there you mostly care about the right type of the request, and I was in situation of a range error, which is however almost impossible to check under assumption of complete duck-typing.

**Comment by bartvm** [comment]
The difficulty though: I would like it if a user is still able to call `mnist.get_data([13, 17])` to get samples 13 and 17. On the other hand, I don't want to re-implement `if isinstance(request, list): return self.X[request]` for each `get_data` method...

**Comment by bartvm** [comment]
Oh, that was a cross-post. A range error? How come it was so hard to debug, shouldn't that just say something like "request blabla out of range in MNIST.get_data"? I think it's really overkill to start adding explicit range checks everywhere. The standard `IndexError` should be enough.

**Comment by rizar** [comment]
Because it does not throw a range error for a slice!

**Comment by bartvm** [comment]
Ah, that's true, I was just thinking of lists of indices... So you're suggesting to add a `if isinstance(request, slice) and request.start >= self.num_examples: raise ValueError` check somewhere?

**Comment by rizar** [comment]
That would do the job, but what do you think about simply not using slices for this purpose? The memory overhead is negligible, but all the indexing errors will cause immediate crashes.

**Comment by bartvm** [comment]
Sounds good to me.

**Comment by rizar** [comment]
OK, I will do a PR at some point.

**Comment by bartvm** [comment]
Fixed in 0950a0e378d1a0869a055cca3c10020a780cc0a5.
