### ISSUE TITLE
Order of Arguments for IsotropicGaussian

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#123]
That's a really minor thing, but anyway: when I write `IsotropicGaussian(0.01)` I expect it to have zero mean and 0.01 standard deviation, which is currently the other way round. Should I fix that?

**Comment by bartvm** [comment]
I don't have much of a preference, but I guess that it would make sense to stick with e.g. the NumPy and Theano interface, which both take the mean as the first argument (http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.normal.html and http://deeplearning.net/software/theano/library/tensor/raw_random.html#raw_random.RandomStreamsBase)

**Comment by rizar** [comment]
Okay, let's wait until we have users and can make polls :)

**Comment by rizar** [comment]
Well, I stumbled upon this one more time!  I have a good argument why in our case the standard deviation should go first: because `IsotropicGaussian` is an initialization scheme, and in the context of weights initialization sigma is always zero.

**Comment by bartvm** [comment]
I ran into it the other day as well actually, I'm happy to change it!

**Comment by bartvm** [comment]
Fixed in #164.
