### ISSUE TITLE
Additional cost?

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#126]
Question for @janchorowski, but maybe @rizar knows as well: What are the variable roles "cost" and "additional cost" supposed to represent, and how are they different? Can we done with one of the two? If not, we probably need some documentation as to why.

**Comment by janchorowski** [comment]
The idea was that: the cost is for the main cost, like 
neg-log-likelihood. Additional costs are for e.g. L1 penalty for 
activations in a certain layer. Or in my speech net for the penalty on 
lagging alignments. The main difference, that "costs" are returned 
directly from brick.apply methods. "Additional costs" are returned via 
the apply_call tag auxiliary outputs mechanism - they are a sideproduct 
of the brick application.

**Comment by bartvm** [comment]
Got it! Maybe it's an idea to rename it to "penalty" so that it is clear that they refer to regularization terms?

**Comment by rizar** [comment]
Or alternatively we can just delete it until we have a real example which uses it. For it is rather obscure currently how it can be applied.

**Comment by bartvm** [comment]
Maybe the way we assign roles should be slightly different. Thinking about it, I don't think we can easily divide variables into these exclusive classes (input, output, cost, additional cost, and monitor) e.g. for all cost bricks, the output is both an output, a cost, and a monitor. (Basically, any auxiliary variable *can* be monitored.) Maybe this scheme would make more sense:

We have inputs and outputs, and auxiliary variables. Both outputs and auxiliary variables can be costs (for this they must be scalar). Any auxiliary variable is a potential monitor (cost or no cost).

This would allow us to very simply:

* Request all possible regularizers and loss functions
* Request all auxiliary variables (i.e. anything that might be worth monitoring which doesn't go in or out a brick)

**Comment by rizar** [comment]
May I just reformulate your point: a variable can have multiple roles. Let's have a list of roles for every variable then, why not?

**Comment by bartvm** [comment]
Yes, (a) a variable can have multiple roles (although input and output are de facto probably exclusive), but also (b) get rid of the monitoring role; anything that is auxiliary is automatically a potential monitoring variable.

**Comment by rizar** [comment]
I am fine with (b). I think we should add new roles as they become necessary, and since currently no code sample is using fine-grained categories "additional cost" and "monitor", I would not mind cleaning this categories away.
