### ISSUE TITLE
Language modeling example with different types of RNN

### ISSUE THREAD

**Issue by lvapeab** [bartvm/blocks#130]
Hi all,

firstly, I want to congratulate you for your great work. Although I'm still newbie in Theano, I find this approach really nice. But I'm having some issues as I try to get everything working:

I'm trying to test the language model example with other types of RNN, such as (simple) Recurrent or Bidirectional layers, but I can't get it. I use a Bidirectional layer (with Recurrent or GatedRecurrent), and the problems arise in the construction of the SequenceGenerator, more preciselly, at the invocation of  `__getattr__` in `/blocks/bricks/__init__.py`, where it throws an `AttributeError` (line 672).

Do I have to perform some specific configuration in the bidirectional layer or in the sequence generator?
Is it possible with the provided means to implement a Bidirectional network able to model language? What did I miss?

Thank you very much! :)

**Comment by rizar** [comment]
Hi, 

thank you for your interest in blocks!

In fact the `Bidirectional` is not a recurrent brick: it sticks two recurrent bricks together to make a bidirectional network. So it is very natural that it does not work. I am not aware of any paper where language would be modelled by a bidirectional network. The approach should be radically different from the traditional one, where the next token is predicted given the previous ones.
