### ISSUE TITLE
Should recurrent bricks attach updates to application_call instead of scan apply node?

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#140]
For two reasons:
* Right now updates are spread over two places, which is confusing
* It will circumvent the bug holding up #75, which can actually make a huge difference for some models

**Comment by bartvm** [comment]
Just remembered @rizar already commented on this:

> An alternative would be to attach updates to the ApplicationCall, but this does not cover the case when a user uses scan in an intermezzo between two blocks-based parts.

Although I agree, I think that should be okay. If a user doesn't use a brick in a particular segment, they can also add the updates themselves to the algorith manually using the `add_updates` method; simple enough step.

**Comment by rizar** [comment]
After a few minutes of thinking I came up with an example where you can not simply add updates: what if you have updates in a computation graph of a variable monitored on an auxiliary dataset? There's no `add_updates` for it so far. 

We could use "fake" application call objects for this purpose. That would also allow to add auxiliary variables to the graph without using bricks.

**Comment by rizar** [comment]
I had a sort of revelation and now it seems I see the big picture: let's introduce a notion of an annotation of a computation graph. An annotation is a bunch of auxiliary variables plus updates. The `ApplicationCall` becomes a subclass of the `Annotation` class. 

The fascinating thing coming from doing it this way is that the computation graph module should know nothing about bricks. It simply works with an annotated graph. The user can just work in bare Theano, add annotations and still benefit from using the framework.

**Comment by bartvm** [comment]
Wait, I'm not sure I follow entirely: The `ApplicationCall` is a subclass of `Annotation`, but what functionality does it have that `Annotation` doesn't? And what do we attach `Annotation` to? To the `ComputationGraph` object?

Does this mean that you want to apply selectors to the `ComputationGraph` instead of to the `Brick` hierarchy?

**Comment by rizar** [comment]
In addition to carrying auxiliary variables and updates an `ApplicationCall` instance also has references to the brick and to the application. We can attach annotations to the variables exactly in the same way `ApplicationCall`'s are currently attached, just that some of these annotations will be also instances of the `ApplicatoinCall` class. 

No, I do not want to apply selectors to the CG.

**Comment by bartvm** [comment]
Closed through #141.
