### ISSUE TITLE
More DataStreamWrappers!

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#148]
As discussed in #114, we need a whole lot of them. Good thing about writing such things is that it can be split up into parts. 

I would put priority on the following ones: 
a) one that splits a data stream into batches 
b) one to pack lists of lists of lists of ... of tuples of whatever into tuples of numpy arrays and masks.

Having those would make it possible to finally train a demo with an attention mechanism.

**Comment by bartvm** [comment]
Both those have been introduced, so probably need more tickets with specific requests.
