### ISSUE TITLE
Error handling of main loop

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#154]
More small things regarding the main loop: Right now the `after_training` extensions are run whenever an error occurs during training (because it's in the `finally` block). I'm just wondering whether this is the correct thing to do; maybe another event should exist for this e.g. `on_error`?

For example, I was having errors with pickling again (recursion limit), which means that the error got caught, the `Printing` extension got called and suddenly said "Training finished!", after which the `SaveLoad` extension tried to save the model, crashing again. It took me a while to figure out what was happening here. I guess that in general we should:

* Give a warning, saying that an error occurred, but that we are trying to run some extensions before exiting
* Call the extensions with the `on_error` event, so that they can behave differently
* Save the model to a different file; we don't want to be overriding a good model with a broken one if the error was e.g. a filesystem error.

**Comment by rizar** [comment]
That sounds reasonable, it is especially bad that we corrupt a good model now when an error happens.

**Comment by bartvm** [comment]
Partially addressed in #158 (still needs saving to a different model on interrupt).

**Comment by bartvm** [comment]
I think all the of these issues have been resolved.
