### ISSUE TITLE
MNIST example without Bokeh

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#174]
Originally mentioned in #173, also related to #170 (run tests with Bokeh as well).

**Comment by AjayTalati** [comment]
HI,

I'd like to run the MNIST example without Bokeh as I can't get it to work with Bokeh? 

Here's the error screen.  

![bokeh_error_for mnist_example](https://cloud.githubusercontent.com/assets/10279780/6800173/061cf3ae-d214-11e4-9eeb-000bc1caba93.png)


As mentioned in #173 above - for a first example of using Blocks - what's the point of requiring extra stuff at such an early stage?
