### ISSUE TITLE
Algorithm can't write to current row in log

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#179]
@rizar It seems that `self.status.iterations_done += 1` is called *after* `process_batch`. I was trying to output the step size taken by my algorithm to the log, but if I write to `log.current_row` it won't show up in the logs, because I was actually writing to the previous row.

Is this by design? Or can I move `self.status.iterations_done += 1` just to the line before `process_batch`?

**Comment by rizar** [comment]
That's a design choice we should make: what is our time scale and when should extensions and/or algorithm write to previous, current, or maybe even the next row.

Currently the time counter indicates the number of parameters updates done. That's why it's incremented after the batch is processed. I would prefer to keep like this because it is very clear. Alternatively we could include the `after_batch` extension call in the iteration. Moving the counter before `process_batch` makes it hard to interpret what an iteration is.

Another consideration is: should the training algorithm write to the log at all? Currently it has access to the log but does not use it. Maybe it is better to keep the algorithms completely agnostic to the main loop and the log? To output the step size you can use the `TrainingDataMonitoring` extension. This constraint would promote people to equip their algorithms and step rules with nice interfaces, which would result in higher reusability of Blocks code.

**Comment by bartvm** [comment]
At first sight, I don't like the idea of forcing the algorithm to not use the log. In my case, when working on optimization, I have all sorts of non-Theano stuff going on (calls to SciPy functions, my own code, etc.) which spit out step sizes, eigenvalues, convergence rates, etc. that I want to monitor. Right now `TrainingDataMonitoring` only accepts Theano variables, and I shouldn't need to convert all these numerical values to Theano shared values just to put them in the log.

So that leaves two options:

Giving training algorithms access to the loop, and make `current_row` mean "The iteration that is currently being performed". That makes more sense to me than the current semantics. I guess there is just a discrepancy between `iterations_done` (which should be incremented at the end of the iteration) and `current_row` (which should be incremented at the beginning of the iteration).

The second option is changing the `TrainingDataMonitoring` extension to accept non-Theano variables through e.g. callbacks. That way each algorithm could provide (a) Theano variables to be read and (b) a callback that will return a dictionary of values to store in the log.

I prefer the first option because I want to be able to write code like:

```python
for i in range(maxiter):
    if step < rtol:
        eigenvalue = something_complicated()
        log.minimum_eigenvalue = eigenvalue
log.eigenvalue_convergence_steps = i
# Etc, with at least half a dozen of other things that I want to monitor.
```

**Comment by rizar** [comment]
While I understand that in the short term it would be convenient for you to write directly in the log, I am afraid of the consequences it might bring. If you write your monitoring values directly to the log, that makes your algorithm not fully usable without the log. It contradicts the "star-shaped-dependency" graph idea and it makes it harder to view Blocks as a toolbox. 

Alternatively, you can do like that in your algorithm object:

```
for i in range(maxiter):
    if step < rtol:
        eigenvalue = something_complicated()
        self.minimum_eigenvalue = eigenvalue
self.eigenvalue_convergence_steps = i
```

and then uses an extension:
```
extensions=[..., MonitorAttributes(algorithm, "minimum_eigenvalue"), ...]
```

I think it is clear enough.

P.S. Still owe you an answer on how to treat the `current_row` thingy.

**Comment by bartvm** [comment]
Okay, fair enough. I thought for a minute that the algorithms were supposed to have access like the extensions, but on second thought you're right, that's not a good idea.

Not a big fan of the attribute monitoring, I'd prefer a kind of callback system because sometimes you will not want to calculate certain values if they're not monitored. So I guess you will want it to look more like:

```python
extensions=MonitorAlgorithm(algorithm, ['minimum_eigenvalue', 'step_size', 'something_complex'])
```
```python
class ComplexAlgorithm(TrainingAlgorithm):
    ...
    def monitor(self, channels):
        values = {
            'minimum_eigenvalue': self.minimum_eigenvalue,
            'step_size': self.step_size
        }
        if 'something_complex' in channels:
            values['something_complex'] = self._very_heavy_method()
        return {channel: values[channel] for channel in channels}
```

**Comment by rizar** [comment]
>> because sometimes you will not want to calculate certain values if they're not monitored.

Haven't thought of it, good point. Okay, we can do it with `MonitorCallbacks` extension. If we do not care about averaging and aggregation for monitoring channels other than Theano variables, they are very easy to support.

**Comment by rizar** [comment]
So we decided that algorithm should not write to the log, but instead an extension can somehow pick up the values from the algorithm and push them to the log.

**Comment by bartvm** [comment]
We should probably open up a new ticket for this though, and implement it or at least document how this interaction should work, before people start hacking things together. It's a pretty important feature, since we will want to start monitoring learning rates, momentum, etc.
