### ISSUE TITLE
SteepestDescent conceivably bakes learning rate constant into graph

### ISSUE THREAD

**Issue by dwf** [bartvm/blocks#182]
In looking how to implement other learning rules, I noticed SteepestDescent is baking the learning rate into the graph as a constant. This is bad because it doesn't allow for learning rates to be updated on a schedule, or changed during training for other reasons.

I can see a few ways of addressing this:

* Have the StepRule own a shared variable that other objects can modify.
* Simply change the documentation to encourage users to pass in a shared variable or symbolic expression; then some other sort of object can own the shared variable or symbolic expression. 

I suppose that an object that inherits from both `Brick` and `Extension` can be used to provide a gradually annealed learning rate. If this sounds like a good direction I'll send a pull request when I get a minute.

**Comment by bartvm** [comment]
I guess that we can just copy Pylearn2's approach here, and give the `StepRule` a shared variable. We can then implement all sort of learning rate schedules through extensions.

I wouldn't mix `Brick` and `Extension`, the philosophy is very much that bricks help you construct a Theano graph, but that by the time that you start the main loop, the dependencies on that part of the library are minimal/non-existent.

**Comment by rizar** [comment]
Making the learning rate accessible as a shared variable attribute to the `StepRule` seems like a good solution to me.

**Comment by rizar** [comment]
Solved by #192
