### ISSUE TITLE
Re-enable landing page

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#188]
I created a landing page: bartvm@863723ee4b867a64794d83f185b8f3b78c6778c0, accessible at https://bartvm.github.io/blocks/

Overkill or not? :)

**Comment by dwf** [comment]
Heh, a little out there.

Also, gh-pages.zip?

**Comment by rizar** [comment]
Looks cool, maybe even too cool for what we currently have :)

> Blocks is a Theano toolkit developed by students and researchers from the LISA machine learning 
> laboratory of the University of Montreal

I don't care much because I will join the lab soon, but @janchorowski was at the roots of the undertaking and is neither a student nor a researcher at UdeM.

**Comment by bartvm** [comment]
I fixed the link and updated the text to include "collaborators". I'll also take it offline (moved it to d6d5a0d0d0584111df32b731b88529fc287046f3), but we can put it back online when we're just a bit more stable and functional. Might as well sell it well and gain a few users/developers, right? :innocent:

**Comment by rizar** [comment]
Definitely, it makes a very good impression, just a bit too good  for the state of the library.
