### ISSUE TITLE
Should we add `.pkl` automatically?

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#189]
If we always store the main loop in .pkl files, maybe we can relieve the user from specifying the extension? There are four options I see:

* user must add .pkl but we do not check it

* user must add .pkl and we even check it

* user can add .pkl, but if he didn't, we do it for him

* user should not add .pkl, and if he adds, there will be a double extension .pkl.pkl

What do you guys prefer? 

I came to this question because I wanted to add an option to the `SerializeMainLoop` extension to save additionally a pickled model and/or a pickled log and was considering different options of how to name those files.

**Comment by bartvm** [comment]
I would go for the same interface Python has regarding file names and not try to add any sugar on top, so just expect the user to add `.pkl` or whatever extension he/se wants.

**Comment by rizar** [comment]
Okay, suppose I want to add an option to `SerializeMainLoop` to save the model separately. How do I form the path for the model without making any assumptions about the path given by the user? E.g. if the path for saving the whole main loop is `mainloop.pkl`, I would like to save the model as `mainloop_model.pkl` and do as little parsing magic as possible.

**Comment by bartvm** [comment]
```python
root, ext = os.path.splitext(main_loop_filename)
model_filename = root + '_model' + ext
```

**Comment by rizar** [comment]
OK, I see it can handle the case of an empty extension.
