### ISSUE TITLE
Check at Least One Batch in an Epoch

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#201]
Subject.

**Comment by dwf** [comment]
Check*

Although the description isn't that clear to me even with the spelling corrected. Do you mean, "check that we have processed at least one batch at the end of an epoch, and raise an error if not?"

**Comment by rizar** [comment]
We should raise an error if an epoch iterator became exhausted without yielding any example. Such behavior breaks certain assumptions and should be explicitly unsupported.
