### ISSUE TITLE
Extension docstring clarification

### ISSUE THREAD

**Issue by dwf** [bartvm/blocks#202]
https://github.com/bartvm/blocks/blob/master/blocks/extensions/__init__.py#L134

Am I correct in assuming that the `after_n_*` are triggered only once? If so, it might be good to explicitly state it.

**Comment by rizar** [comment]
Currently it is triggered only once as the condition is ` log.status.epochs_done == n_epochs`. But that was a rather arbitrary choice, and perhaps it is better to change to it to ` >= ` there. The main example when this condition is used is the `FinishAfter` extension, and currrenly one can continue a main loop that was finished on this condition, as it will not be met any more at the following iterations. This is sometimes convenient, but more confusing, I guess.

So, should we switch to `>=` here, @dwf , @bartvm ?

**Comment by bartvm** [comment]
I guess that switching to `>=` might make more sense for use cases where you want to e.g. only start saving your model after a certain number of epochs.

What do you propose to do with `FinishAfter` not matching anymore though? I guess that we can always add a custom predicate, `log.status.epochs_done == n_epochs`, for that particular extensions; we don't need to turn each possible predicate into a keyword argument after all.
