### ISSUE TITLE
every_n_epochs

### ISSUE THREAD

**Issue by dwf** [bartvm/blocks#203]
Seems like `every_n_epochs` is missing. You could of course implement this with a counter in your object state but you could make the same argument for `every_n_batches`.

**Comment by bartvm** [comment]
Yeah, don't know why that one isn't there. Might as well just add it to the list.

**Comment by rizar** [comment]
Yeah, definitely, just add it and we merge straight away. The list of conditions is in no way exhaustive and will grow some more incorporating all typical usecases, such as yours.

Another thing: I changed my mind and think that we should refactor `SimpleExtension` a bit and handle all trivial conditions in a homogeneous way as @bartvm suggested. A loop through `kwargs` seeking for callback names would be a nice way to do that, IMHO.
