### ISSUE TITLE
SGD with Momentum and Required Refactoring

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#205]
I wanted to implement SGD with momentum and realized that current `StepRule` interface is still very far from perfection. In order to implement it one has to add some updates that have gradients on their right hand side, but the `additional_updates` method from [here](https://github.com/bartvm/blocks/blob/master/blocks/algorithms/__init__.py#L255) has no parameters. There are a few possible options I see:

1. Add gradients a parameter to `additional_updates`. That would solve the problem, but potentially can lead to a lot of code duplication between this method and `compute_step`. 

2. Change the `compute_steps` return value, make it return both the step and the updates. Eliminates the problem with code duplication at the cost of a slightly more complex interface.

3. `compute_steps` determines the updates and stores them as the object's attributes, these attributes are returned by `additional_updates`. Does not require any change of interface, no code duplication, but adds a life-cycle to an otherwise stateless object.

4. A radical solution - follow the PyLearn2 way of doing things and have `StepRule` return updates only. I mention it for completeness, but it seems to be inappropriate because there is no way to chain different rules.

I am inclined to follow the path number (2), because it allows to make the `StepRule` stateless, which I think would be nice. All the shared variables can be created in the `compute_steps` call. The returned value of `compute_steps` would then deserve a name, e.g. `GradientStep`, and can also have additional attributes for monitoring purposes.

**Comment by dwf** [comment]
Option 1 needn't lead to a lot of duplication with the right auxiliary methods, which could be provided by `StepRule` once it's clear what the useful primitives are. But I agree with you that 2 seems most attractive.

**Comment by bartvm** [comment]
@rizar Was this fixed in #210?

**Comment by rizar** [comment]
Sure!
