### ISSUE TITLE
Timing Extension Has to Be Split into Two

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#206]
While writing the `Timing` extension we currently have I realized that in the current paradigm there is no way it can be implemented as a single extension. E.g., in order to measure time spent on "after_batch" callbacks
one has to start measurement in one of these callback and to finish it in another. What is currently done instead is quite ugly and the resulting number are useless.

That is we should either hard-code timing into the main loop or have it done by two extensions. But making the user every time to put both `TimingStart` and `TimingFinish` in the extension list is inhumane. So I guess if we go for the latter choice, we should finally have some extension added by default. As for moving timing to the main loop, I am afraid this could make it rather cluttered.

**Comment by bartvm** [comment]
I'm okay with adding default extensions. (We could eventually make them optional with a flag like `default_extensions=True`, but I can't think of an essential use case where you would want to turn off timing.)

**Comment by rizar** [comment]
The thing is one might need different level of verbosity. So by default we should only add very essential timing, as for the more complex option, like measuring CPU time of `after_training` call, one would have to add manually two extensions. But I guess it's okay, pay for what you use basis.

**Comment by rizar** [comment]
Not relevant after #552
