### ISSUE TITLE
Toolz?

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#223]
Does anyone have any objections to using toolz? It would mean a (tiny) extra dependency, but a lot of its functions can come in handy from time to time. For those that don't know it: http://toolz.readthedocs.org/en/latest/api.html. It's very stable, and used in a lot of libraries.

**Comment by rizar** [comment]
An specific example of how we can use it?

**Comment by bartvm** [comment]
Sadly we can't use it in as many places as I'd like, because we deal with `OrderedDict`s a lot, but anyway, here's a just one or two refactors that I quickly found, but I'm sure there are more places: #226

**Comment by rizar** [comment]
Okay, looks good. Though I am slightly confused by double standards: you discourage using `map` and `filter`, but you are fine with functions from a third-party library.

**Comment by bartvm** [comment]
Yes, because there are directly alternatives to `map` and `filter` in Python, and for people unfamiliar with `map` and `filter` the list comprehension syntax is actually much easier to read (and considered more Pythonic). However, interleaving a list by chaining `list`, `chain` and `zip` with a splat operator is in no way easier to read than `interleave`.

**Comment by rizar** [comment]
Okay, let's keep it like this. 

```
   There should be one-- and preferably only one --obvious way to do it.
    Although that way may not be obvious at first unless you're Dutch.
```

**Comment by bartvm** [comment]
For the `mapcat` example I agree that the original might have been clearer; I was just quickly looking for an example where `toolz` could come in handy. I could change that back. 

However, for the `interleave` example I disagree. Map and filter are pretty universally discouraged (it's even [part of PyLint](http://pylint-messages.wikidot.com/messages:w0141)) because there are direct and clean alternatives in Python in the form of list comprehensions. However, there is no direct and clean alternative for interleaving two lists, so there is no reason not to replace the very obscure `list(chain(*zip()` with `interleave`.

**Comment by bartvm** [comment]
* And likewise for `sliding_window`

**Comment by rizar** [comment]
Okay, I do not care too much. I just think that `map(str.split, file_)` is more readable than `[str.split(line) for line in file_]`, but that can be disputed, whereas `interleave` definitely wins over `list(chain(*zip()))`.

**Comment by dwf** [comment]
I'm with @rizar (though I've flip flopped through the years). Definitely
more Pythonic but that doesn't necessarily mean more readable; there's
definitely a cognitive load introduced by a new free variable. (Anyway...)

**Comment by bartvm** [comment]
I think it very much depends on how comfortable and familiar you are with functional programming, since to me `[str.split(line) for line in file_]` is clearer. It is explicitly made clear that there is a loop over the lines in the file being performed, whereas with `map` this loop is entirely implicit. This means that (a) I need to know that `map` performs a loop and (b) I need to know that each element in the loop over a file is a single line. The list comprehension syntax makes the loop itself explicit, while also making clear what the elements in the loop represent. 

I think that this mostly points out that it's a matter of syntactic preference. But since we're writing a publicly-available framework we might as well stick with what is most commonly considered good practice, and both PyLint as well as the [official Python guide](https://wiki.python.org/moin/PythonSpeed/PerformanceTips#Loops) are quite clear about that:

> Besides the syntactic benefit of list comprehensions, they are often as fast or faster than equivalent use of map.
