### ISSUE TITLE
Add data set loading/configuration to tutorial

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#228]
Right now the tutorial uses MNIST but doesn't explain which files to download, where to put them, and how to set the data path.

**Comment by arasmus** [comment]
I just set up the thing, so I'll share here what were the steps required. Maybe it's helpful. I don't know whether you have plans for automatic data download scripts (which travis could use too) or simply instructing users to do something like this:

```
echo "data_path: /Users/rasmusa/code/datasets" > ~/.blocksrc
mkdir -p /Users/rasmusa/code/datasets/mnist
cd /Users/rasmusa/code/datasets/mnist
curl -O http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz \
             -O http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz \
             -O http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz \
             -O http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
gunzip *
```

**Comment by bartvm** [comment]
We discussed automatic data downloading scripts, which resulted in #105. I feel that we shouldn't make them part of the core library, to make sure we stay small, but if we could do it with a minimal dependency on `skdata` then it's worth considering.

**Comment by rizar** [comment]
Yep, that's the current policy. But instruction for getting dataa should be part of the tutorials and/or documentation.

**Comment by bartvm** [comment]
Yeah, I consider that part of this issue. I should probably change the title, but it's in the description :)

**Comment by bartvm** [comment]
Added in 04914ba306c09d7eff200490d67b39ddd2ec50ce
