### ISSUE TITLE
Unsupervised learning / ignoring targets provided by a dataset

### ISSUE THREAD

**Issue by jbornschein** [bartvm/blocks#230]
Maybe I'm just missing something and this is a question, rather than an issue:

GradientDescent.process_batch  will raise an exception if the batch contains data that is not used in the cost graph. But in unsupervised learning we really don't care about the targets.

https://github.com/bartvm/blocks/blob/89190b22c7276f643e4759c469fcee358fa46765/blocks/algorithms/__init__.py#L201

What's the best way to deal with this? Should the dataset be explicitly "filtered" to only contain those variables the cost function is interested in? Or should it be sufficient for the cost function to use at least one variable of the dataset? Or is there another solution?

**Comment by bartvm** [comment]
You should be able to filter any dataset to only provide the sources you need by passing the `sources` argument, which is documented [here](https://github.com/bartvm/blocks/blob/master/blocks/datasets/__init__.py#L22-L24).

Without having given it too much thought, I think this is probably a good design choice. This way a user will get an error if he's passing data that he *thinks* his model is training on, but actually isn't.

We should probably make the error more informative though, giving a bit more detail about how to restrict the dataset from providing particular sources. So let's keep this issue open.

**Comment by jbornschein** [comment]
I submitted a pull request (#232) to make the exception more verbose and more helpful:

```
ValueError: The names of the input variables of your computation graph (features) must correspond to the data sources (features, targets). Maybe your Dataset supports the 'sources' keyword to explicitly select which sources you want?
```

I guess this touches two policy question:

1) Do you want more verbose exceptions at the cost of more complex error handling code?
2) Writing unit tests for these branches seems overkill to me, but not writing them will decrease test coverage.
