### ISSUE TITLE
Serialization and reproducibility 

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#236]
At the risk of (re-)opening a can of worms, I wanted to bring up the topic of serialization and reproducibility once more. (Mostly following a lengthy discussion on Pylearn2 yesterday where many issues regarding reproducibility reared their head, and my frustrating experience with serialization and `into` yesterday.)

So here's the proposition:

> Should we relinquish complete reproducibility for the sake of clarity of code and ease of development? Instead of aiming for checkpointing at any point we could e.g. aim to support completely transparent checkpointing **only between epochs**.

## Pros

* Clarity of code; probably best illustrated by examples (see end).
* Ease of development; fewer peculiarities that new developers need to get familiar with e.g. no generators, no lambda expressions, etc.
* Full reproducibility is only relevant in a limited number of cases; in these cases, you would simply have to make sure that you only restart in between epochs.
* We could possibly switch to a single serialization method instead of having to maintain two.
* Possibility of using `pickle`/`cPickle` instead of `dill`; `dill` tends to crash because it exceeds the default maximum recursion depth.

## Cons

* Results won't be entirely reproducible, while reproducibility should be the hallmark of scientific experimentation; this could be especially problematic for experiments where epochs don't exist (infinite datasets) or where epochs are particularly long (order of days).
* Our serialization protocol will be more involved; the current serialization is limited to a single `dill.dump` call.
* Users might not realize the full effects of stopping and restarting their experiments; they could be training only on the first half of a large dataset because they keep restarting, not realizing their epoch iterator won't be restored

## Proposal

* If aiming for full reproducibility in between epochs only, we don't need to serialize the dataset iterator (epoch iterator) or the dataset's state. The data stream can simply delete its state when pickled, by default.
* We could let states implement a `__getstate__` method, allowing datasets to support a form of checkpointing nonetheless if they do so explicitly.
* The current secondary serialization method would have to be extended to include the state of training extensions (e.g. momentum, moving averages). This too could be implemented by requiring these extensions to implement `__getstate__` and `__setstate__` methods, or simply by pickling them (assuming that we will still pickle the Theano graph instead of dumping variables).

I am not entirely convinced that the parameter dump we have implemented right now would be a good replacement for pickling the Theano computation graph though. We might still want to support two separate methods there (as well as push for #2339 to be merged).

## Examples

These are some examples of what code looks like right now in the library, and what it could look like if we no longer had to worry about serializing in the middle of an epoch.

```python
class TextFileState(object):
    pass

class TextFile(Dataset):
    ...
    def open(self):
        state = TextFileState()
        state.current_index = 0
        state.file = self._open_file(state.current_index)
        return state

    def get_data(self, state=None, request=None):
        ...
        while True:
            if state.file is None:
                raise StopIteration
            sentence = state.file.readline()
            if not sentence:
                state.file.close()
                state.file = None
                if state.current_index == len(self.files) - 1:
                    raise StopIteration
                else:
                    state.current_index += 1
                    state.file = self._open_file(state.current_index)
            else:
                break
```
```python
class TextFile(Dataset):
    ...
    def open(self):
        return concat(into(Iterator, TextFile(filename)) for filename in self.files)


    def get_data(self, state=None, request=None):
        ...
        sentence = next(state)
```
---
```python
class LambdaIterator(six.Iterator):
    def __init__(self, next_function):
        self.next_function = next_function

    def __iter__(self):
        return self

    def __next__(self):
        return self.next_function()
```
```
```
---
```python
class ConstantScheme(BatchSizeScheme):
    def __init__(self, batch_size, num_examples=None, times=None):
        if num_examples and times:
            raise ValueError
        self.batch_size = batch_size
        self.num_examples = num_examples
        self.times = times

    def get_request_iterator(self):
        return ConstantIterator(self.batch_size, self.num_examples, self.times)


class ConstantIterator(six.Iterator):
    def __init__(self, batch_size, num_examples=None, times=None):
        if num_examples is not None and times is not None:
            raise ValueError
        if times is not None or num_examples is not None:
            if not ((times is None or times >= 1) or
                    (num_examples is None or num_examples >= 1)):
                raise ValueError
            self.current = 0

        self.batch_size = batch_size
        self.num_examples = num_examples
        self.times = times

    def __iter__(self):
        return self

    def __next__(self):
        if self.times or self.num_examples:
            if self.current == self.times or self.current == self.num_examples:
                raise StopIteration
            if self.times:
                self.current += 1
            else:
                batch_size = min(self.batch_size,
                                 self.num_examples - self.current)
                self.current += batch_size
                return batch_size
        return self.batch_size
```
```python
class ConstantScheme(BatchSizeScheme):
    def __init__(self, batch_size, num_examples=None, times=None):
        if num_examples and times:
            raise ValueError
        self.batch_size = batch_size
        self.num_examples = num_examples
        self.times = times

    def get_request_iterator(self):
        if self.times:
            return repeat(self.batch_size, self.times)
        if self.num_examples:
            d, r = divmod(self.num_examples, self.batch_size)
            return concat(repeat(self.batch_size, d), [r] if r else [])
        return repeat(self.batch_size)
```

## Thoughts?

How important is reproducibility and checkpointing, really? Is it worth the effort we put in right now? Or does the maintainability and clarity of the framework weigh heavier? Considering the amount of changes this would need, I think we should make this decision before the framework grows much larger, because it will only become harder to refactor.

**Comment by rizar** [comment]
> We could possibly switch to a single serialization method instead of having to maintain two.

I do not see how it would help to get rid of dumping. Pickle files are just a bad way of storing and sharing data, but they are very interesting for us because of guarantees they provide. If you want to share a model and a training log from your experiments with the scientific communitiy, putting a pickle file is a very bad option, but if you want to resume a training after a server failure, this is the best option.

**Comment by rizar** [comment]
Although I have to sleep through this text and reconsider the arguments in emotionless way, currently I feel that you are targeting something entirely holy for me: the ability to press Ctrl + C in any moment without any fear of data loss. I believe this was one of the killing features of the Groundhog making people prefer it to PyLearn2. So I will try to think in the direction of making both of us happy: reducing code complexity with keeping this important and distinctive feature of the framework.

**Comment by bartvm** [comment]
Well, that's why I said "We might still want to support two separate methods there." I agree that for parameter dumping there is a strong case to use both methods in parallel.

The main proposal here is to no longer pickle the request iterator, data iterator, and state of the data stream by default, hopefully decreasing code complexity significantly (see my examples). That means you can still save the parameters in the middle of an epoch, but when you resume training the epoch will be reset.

The downside is clearly for cases where we have very large datasets, and an epoch can take several hours. For those cases I suggest implementing a custom picklable state (and ensure that the dataset does not require a request iterator).

With some luck, this might even allow us to switch back to `pickle `, which is faster and is less likely to run into recursion errors.

**Comment by bartvm** [comment]
Cross-posting again, but I agree that you should still be able to press Ctrl+C at any time and that your parameters should be maintained. The only question here is whether we care enough about resuming training at the *exact* sample we were to justify the code complexity it brings with it.

I'm starting to feel that the cases in which this is truly important are not common enough, and are easily fixed with a custom `__getstate__`.

**Comment by bartvm** [comment]
A suggestion made by @dwf: In order to alleviate the complexity that stems from not being able to use things like `chain`, `repeat`, etc. perhaps it's worth it to bite the bullet and implement a "picklable itertools" package (potentially in a separate repository). If we have picklable, general purpose implementations of `chain`, `repeat`, `izip`, `imap` and `ifilter` it could potentially simplify the code of the data streams and schemes a lot. I think it's definitely worth considering if we're not willing to give up the seamless checkpointing.

**Comment by dwf** [comment]
http://github.com/dwf/picklable_itertools oh god what have I done

**Comment by rizar** [comment]
> (and ensure that the dataset does not require a request iterator).

I am afraid it does not work. Suppose I am testing a revolutionary new model on MNIST, it is super nice but a training epoch lasts a day. I need shuffling which is implemented by one of the request iterators. That is all request iterators should be picklable.

The data iterator is trivial and only one, so having it picklable comes at a low cost.

As for the dataset states, I think it is OK that if a person is fine with starting from the beginning of the data, the state of his dataset can drop some information before pickling and such a dataset can go to `blocks-contrib`. But the datasets from the library should be picklable, because we do not know in advance for which purpose they will be used.

I like the picklable itertools idea. @dwf , you are so fast!

**Comment by rizar** [comment]
>  but I agree that you should still be able to press Ctrl+C at any time and that your parameters should be 
> maintained.

Not only parameters, everything. It would make me mad to think how dangerous it was to interrupt my data iteration and start it anew. And I think many people will use blocks in for long experiments (machine translation, text-to-speech, speech-to-text, caption generation), and those should be given quite high priority.

**Comment by bartvm** [comment]
I'm well aware of the problems it would cause, but I'm also worried about how hard it makes to develop for the library.

Long experiments like machine translation often don't care about the minutiae of data iteration, since they mostly read linearly through the dataset anyway. On the other hand, I'd be very worried if your algorithm takes a day per epoch on MNIST. The situation where we need interruptible, pseudo-random iteration *and* have long epochs, isn't that common. I think that made it worth opening up a discussion about whether these few cases justify the code complexity and effort we put into data streams.

Let's go with the picklable iterators, I think those are a great idea which address many of the issues.

**Comment by rizar** [comment]
Agreed. 

If the recursion limit problems we have are due to dill, then it would be nice to say it good bye. How much do we depend on it? lambda and files, or something else as well?

**Comment by dwf** [comment]
Note that we've had problems in pylearn2 with the recursion limit,
completely dill-free. Normal pickle has this problem too, to a degree.

**Comment by bartvm** [comment]
Nested functions are another one. For Pickle all objects that are
serialized need to be accessible in the global namespace. I actually
started a branch that removes the dependency on Dill. It will take a bit of
refactoring, and is dragging me deep into the wonderful world of Python's
data model, but so far I haven't run into anything which I think will make
it impossible. One example of an immediate problem is that we currently
replace the "apply" method with an Application class, which keeps a
reference to the unbound "Brick.apply" method. Pickle doesn't like that,
because when it tries to serialize the "application" attribute of an
Application instance, it can't find the unbound method anymore (because
it's been replaced). I think this can be fixed by moving the unbound method
instead of replacing it, but moving it is different in Python 2 and 3
(func_name vs. __name__) so it's a rabbit hole.

Anyway, I think it's still a good goal to have. I know can cPickle also run
into recursion errors, but it seems not to do it as fast as Dill does.

**Comment by bartvm** [comment]
Made two more specific issues as a result of the discussion: #253 and #254
