### ISSUE TITLE
NaN for uninitialized parameters?

### ISSUE THREAD

**Issue by dwf** [bartvm/blocks#244]
A common trick when writing numerical code where you expect some array to be initialized is to initialize all the values to be NaN. If you've got a bug, then, you have a very easy canary in the coal mine. What about this as a way to quickly detect uninitialized parts of a model?

**Comment by rizar** [comment]
Sounds good. Might be confused with "true" nans that emerge during training. But current zeros are even harder to detect.

We could as well use inf, any arguments against or in favour?

**Comment by dwf** [comment]
Well, usually it will be obvious that no training has occurred. We could
also add checks for all(isnan(param)) in some error handling pathway,
conceivably.

**Comment by rizar** [comment]
As soon as we have a NaN in the model, the cost becomes one, the gradients become NaN, everything becomes NaN. 

But anyway I like your idea.

**Comment by bartvm** [comment]
Closed via https://github.com/bartvm/blocks/pull/379
