### ISSUE TITLE
Switch to picklable_itertools

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#254]
Where possible, simplify code by using [picklable_itertools](https://github.com/dwf/picklable_itertools).  The main targets will be data streams and request iterators.

**Comment by rizar** [comment]
Now when I try to do something with already installed blocks I miss picklable_itertools, which I can not install from `pip`. That's inconvenient, I have to reinstall blocks now to get them downloaded, or to clone the repo explicitly.

I think we should either move them to blocks or add to pip asap.

**Comment by bartvm** [comment]
You only need to re-install once, right? I don't think moving them to Blocks is a good idea (they're way more general than that) and adding to PyPI doesn't make much sense right now, as it's still under heavy development without any form of versioning going on.

You should be able to install with `pip` just fine by the way, you just need to pass the GitHub link instead of the package name, just as you would install Blocks:

```bash
$ pip install --upgrade git+git://github.com/dwf/picklable_itertools.git#egg=picklable_itertools
```

**Comment by rizar** [comment]
Okay, I will do something.

But I am very much afraid of this direction of have numerous repositories: blocks, blocks-contrib, picklable-itertools, blocks-datasets. I am not very advanced with all this packaging stuff and many other researchers know even less about it, and working with the cutting edge version will be a hell for them.

**Comment by rizar** [comment]
A continuation of the previous post, sorry for inconvenience.

I feel that it would be better to keep both datasets and picklable_itertools as a part of blocks repo for a while. The main reason is: it is extremely hard to keep track of a project that consists of a few immature parts. You make changes in one, tests are not automatically run in another and you do not know that something became broken. 

I agree, that picklable_itertools are a way more general, but they could be a part of blocks for a few months, until they stabilize and can be separated as a mature project. The same for datasets. Let's not start all this crazy splitting into bits and pieces now: it is to early and will cause unnecessary headache.

**Comment by bartvm** [comment]
Mmm, I don't fully agree. Factoring out early makes things much easier and saves you from having to do search and replace in 50 different files half a year from now. On the short term it will also allow Pylearn2 to use `picklable_itertools` if they want to. Having a single monolithic package is really old school, and for good reasons I think.

As far as packaging goes, I don't think there should be many issues if you set it up properly. You can link to the GitHub repositories in the `setup.py` scripts, so updating at any point would be something like `git pull; pip install -e $PWD --upgrade`.
