### ISSUE TITLE
setup.py fails due to python.h missing (with work-around)

### ISSUE THREAD

**Issue by arasmus** [bartvm/blocks#258]
I open this issue for future reference, in case people will face the same problem. Not sure if this is an issue with my environment or actually something that could be fixed in python dependency installation.

I made a clean clone and did:
```python setup.py develop```

It failed in easy_installation of numpy, because it couldn't find python.h from the system and suggested installing python-dev (Linux system package). However, I don't have admin rights on my computer, so this is difficult.

I worked around the issue by manually pip installing numpy first, which doesn't seem to require that dependency:
```
pip install numpy
python setup.py develop
```

**Comment by bartvm** [comment]
https://github.com/numpy/numpy/issues/2434

We can add this to the installation instructions in case other people run into it.
