### ISSUE TITLE
Plot extensions is incompatible with `blocks-continue`.

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#260]
Before doing any research I will just post this here:

```
╰─$ python `which blocks-continue` mnist.pkl
Couldn't import dot_parser, loading of dot files will not be possible.

-------------------------------------------------------------------------------
TRAINING HAS BEEN RESUMED
-------------------------------------------------------------------------------
Training status:
	 epochs_done: 5
	 iterations_done: 6000
Log records from the iteration 6000:
	 epoch_took: 7.51784586906
	 final_total_took: 86.6179549694
	 iteration_took: 0.00608396530151
	 saved_to: mnist.pkl
	 test_final_cost: 0.133010807013
	 test_misclassificationrate_apply_error_rate: 0.0364
	 total_took: 36.5187389851
	 train_final_cost: 0.135025526067
	 train_misclassificationrate_apply_error_rate: 0.0355666666667
	 train_total_gradient_norm: 0.564584967867

ERROR:blocks.main_loop:Traceback (most recent call last):
  File "/home/rizar/Dist/blocks/blocks/main_loop.py", line 107, in run
    while self._run_epoch():
  File "/home/rizar/Dist/blocks/blocks/main_loop.py", line 153, in _run_epoch
    self._run_extensions('after_epoch')
  File "/home/rizar/Dist/blocks/blocks/main_loop.py", line 174, in _run_extensions
    extension.dispatch(method_name, *args)
  File "/home/rizar/Dist/blocks/blocks/extensions/__init__.py", line 273, in dispatch
    self.do(callback_invoked, *(from_main_loop + tuple(arguments)))
  File "/home/rizar/Dist/blocks/blocks/extensions/plot.py", line 107, in do
    cursession().store_objects(self.plots[key])
AttributeError: 'NoneType' object has no attribute 'store_objects'
```

**Comment by bartvm** [comment]
You could try adding a "output_server" call to "__setstate__" to see if that helps?

**Comment by rizar** [comment]
What should be the `document` argument for it. The documentation says:

```
Args:
    docname (str) : name of document to push on Bokeh server
        An existing documents with the same name will be overwritten.
```

Which means that I can't use the same name as given in `__init__`.

**Comment by rizar** [comment]
After quick consultation of bokeh documentation I got an unpleasant feeling that it is impossible to resume plotting of a document. Do you @bartvm have any information that would suggest the opposite?

**Comment by bartvm** [comment]
Just had a quick look at the Bokeh code, and I'd try `cursession().use_doc(docname)`. Sorry, don't have time to try it myself right now

**Comment by rizar** [comment]
`cursession` returns `None` before an `output_server` call.

**Comment by bartvm** [comment]
What if you try to re-open the session with `Session(name=None, root_url="default")`?

**Comment by rizar** [comment]
And should I use it instead of `cursession`?

I believe it would be much faster if you fix this: would take me some time to understand `bokeh`.

**Comment by bartvm** [comment]
I agree, sorry, I really haven't had much time! I've got an internship interview this afternoon for which I want to prepare a little bit, so even though I've been commenting away, I don't want to dive into coding problems until tonight or tomorrow.

My guess would be to try `bokeh.plotting._default_session = Session(name=None, root_rul="default")` and then use `cursession().use_doc(docname)`.

**Comment by rizar** [comment]
Sorry for pressure @bartvm , it is not so urgent. Fix it when you have time.

Off-topic: where are you interviewed? :)

**Comment by bartvm** [comment]
Phone interview, so I will be speaking to an inanimate object on my desk from the comforts of my living room, while someone is watching every line of code of type... Should be fun! :p

**Comment by rizar** [comment]
Up.
