### ISSUE TITLE
Support more flexible data iteration from multiple sources for semi-supervised learning

### ISSUE THREAD

**Issue by arasmus** [bartvm/blocks#264]
I'm studying semi-supervised learning and I'd like to be able to easily generate datasets for this purpose. E.g. train MNIST with 1.000 labeled samples and 59.000 unlabeled samples. I think supporting this is a reasonable feature for Blocks.

My model is using supervised and unsupervised samples simultaneously, requiring two iteration states, because the data ranges are different. For instance, with batch size 100, I would have 10 labelled mini batches and 590 unlabeled. Epoch would be defined as the number of iterations required to go through the larger dataset. Smaller dataset would be iterated several times during this time, 59 times to in my example.

I'd like to develop a support for this in Blocks and I've done my first draft here to illustrate the requirements. It's still ugly:
https://github.com/arasmus/blocks/commit/c97171e608e708fb4084ccd3284ad80e4ed16ff6

Some design choices:
* Handling of Theano inputs. Because the minibatch content can be different, I need another theano input variable to build the graph properly. I have named it 'features_unsuper' in my first draft.
* Dataset needs to somehow provide a source for that. One would be to augment a new source by using ```DataStreamMapping``` (```add_sources```), but there is no direct way at the moment. Another option is to add new ```provided_sources``` to the existing dataset, but disable them by default. Or maybe they are ignored by default if unused. Or create a separate dataset for semisupervised task.
* One option is to have multiple ```Dataset``` instances and multiple ```DataStream``` instaces attached to the main loop. In this case, iteration schemes don't need to be modified.
* Multiple iteration schemes are required if this is all implemented with-in one DataStream, because some inputs (target and features) has to use one shared iterator and the new 'features_unsuper' has a different pace of iterating. Currently, I've added a possibility to put dictionary as iteration_scheme for ```DataStream```.  A cleaner way would probably be to add a new iteration scheme that supports this dictionary structure and call it something like MultiScheme, AdvancedScheme, SourceSpecificScheme, MultiSourceScheme or something.

What do you think?

**Comment by arasmus** [comment]
A new idea came to my mind to achieve this which is less intrusive.

Simply inherit from MNIST and modify get_data to return a proper slice. This might be difficult in some cases, especially if labeled_samples is not a multiple of minibatch size. But something along these lines

```
@InMemoryDataset.lazy_properties('features', 'targets', 'features_unsuper')
class SemiSuperMNIST(MNIST):
    provides_sources = ('features', 'targets', 'features_unsuper')
    labeled_samples=1000

     def get_data(self, state=None, request=None):
         if state is not None:
             raise ValueError("MNIST does not have a state")
        limited_request = numpy.array(request) % labeled_samples
        return self.filter_sources((self.features[limited_request],
                                    self.targets[limited_request],
                                    self.features[request]))
```

**Comment by bartvm** [comment]
I replied to this by e-mail, but for some reason it doesn't show up here :/

> On my phone now, so I can't look at your code, but in principle this sounds like it should already be supported.

> You will want to write a data stream wrapper which takes as an input two data streams. This wrapper has entire control over how each data stream is used, so you can interleave the two streams as you please.

> The stream would be expected to return two sources at each step though, but you can keep one of the two empty. You then write a custom algorithm which in the `process_batch` method can see which data is actually provided, and chooses what training update is to be performed based on that.

**Comment by bartvm** [comment]
To be a bit more precise, you could write a data stream wrapper which basically does this:

```
def get_epoch_iterator(self, **kwargs):
    super(InterleaveLongest, self).get_epoch_iterator(**kwargs)
    return interleave(self.unlabeled_mnist_stream, chain(repeat(self.labeled_mnist_stream)))
```

Regarding this pseudo-code:

* `interleave` doesn't exist, you end up having to do something like `chain.from_iterable(izip())`
* Both streams will return a tuple, which you need to concatenate, using something like `imap(operator.add, ...)`

**Comment by arasmus** [comment]
Thanks! DataStreamWrapper seems like a good abstraction. I'll study it further.

Actually I don't want to interleave the two streams (if that means taking every other data value from another source), but to use them simultaneously so that one minibatch from each stream contributes to the computation of a single cost function ```cost_final = cost_classification + cost_unsupervised```. I want to be able to combine them into a single gradient update so that all momentums etc work nicely.

**Comment by bartvm** [comment]
Instead of `interleave` you could use something along the lines of `izip` to return batches from both streams. Be sure to look at this PR: https://github.com/bartvm/blocks/pull/256

This should be slightly less pseudo-cody, although far from complete:

```python
@property
def sources(self):
    self.labeled_data_stream.sources + self.unlabeled_data_stream.sources

def get_epoch_iterator(self, **kwargs):
    unlabeled = self.unlabeled_data_stream.get_epoch_iterator()
    labeled = self.labeled_data_stream.get_epoch_iterator()
    combined = izip(repeat(labeled), unlabeled)
    return starmap(operator.add, combined)
```

This should return batches `(mnist_labeled_features, mnist_labels, mnist_unlabeled_features)`, completing the epoch when you run out of unlabeled samples.

**Comment by arasmus** [comment]
Thanks! I’ll try it out!

**Comment by bartvm** [comment]
I'll close this for now because I don't think there's much code in particular to add. Feel free to reopen if you think that there should be some general streams that could be added to the library that would make these kind of things easier.

**Comment by arasmus** [comment]
Agreed, no need for anything - framework already supports this well enough. A custom DataStreamWrapper did the job.

I can add an example to the contrib repo maybe later.
