### ISSUE TITLE
Installation broken; pip doesn't process dependency links without explicit permission

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#276]
Currently `picklable_itertools` is not on PyPI, so it needs to be installed directly from GitHub. `setuptools` allows the keyword argument `dependency_links` for that, which works fine if you use `python setup.py install` or `python setup.py develop`. However, `pip` ignores these links unless you pass `--process-dependency-links`.

We either need to update the installation instructions, or just wait till `picklable_itertools` is on PyPI, which is this ticket: https://github.com/dwf/picklable_itertools/issues/33

**Comment by rizar** [comment]
How long will it takes for `pickable_itertools` to make it to PyPI?

**Comment by bartvm** [comment]
That's a question for @dwf. I'd be happy uploading it today with a warning that says "alpha status" so that the Blocks installation is fixed, and refer the cleaning up to the next few days after which we can upload version 0.0.2, but it's his call.

**Comment by bartvm** [comment]
Just a note that we will have the same problem for [fuel](https://github.com/bartvm/fuel/tree/master/fuel), so maybe we should just add `--process-dependency-links` to the installation instructions for now.

**Comment by rizar** [comment]
Let's do that because people should somehow be able to install Blocks :)
