### ISSUE TITLE
Fix responding to errors, SIGINT and SIGTERM

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#287]
This is just a place to collect the discussions/wish list regarding error handling. It has changed a few times now but after having a closer look I'm still not very happy with it, for a few reasons:

* `SIGTERM` is not handled
* `logger.info` calls are used to report errors (lines [121](https://github.com/bartvm/blocks/blob/f440563fd5c4f8078e9c9003dc2412570a29348f/blocks/main_loop.py#L121) and [126](https://github.com/bartvm/blocks/blob/f440563fd5c4f8078e9c9003dc2412570a29348f/blocks/main_loop.py#L126)); these aren't shown by default, so the user has no idea what is going on. They are errors, so they should use `logger.error`, but...
* `logger.error` calls currently result in mysterious `no handler found` errors with no further information to the user; we either need to use `logging.error()` or call `logging.basicConfig()`
* Right now the first `SIGINT` just tries to finish the batch, but the second one quits halfway the batch and then tries to run the `after_training` extensions, which could screw things up more than it could fix.
* The `on_interrupt` callback isn't used so far, and maybe we should remove it until a good use case comes along?

So, better behavior I imagine would be:

* Call `logging.basicConfig()` in `blocks/__init__.py` to make sure warnings and errors get through
* `SIGINT` behavior:
  * The first one should result in a `WARNING` message, saying that we will try to finish the epoch.
  * A second one will raise a message saying that it will try to finish the batch. In both cases, the `after_training` extensions should be run if we manage to finish the epoch/batch successfully.
  * A third `SIGINT` during training ends the program immediately; no `after_training` extensions will be run.
* `SIGTERM` behavior is to finish the batch and quit (as if two `SIGINT`s were sent).
* An error during the main loop should result in `on_error` extensions being called, but *not* in `after_training` being called. The `on_error` behavior right now is good I think; we should try to run each and every extension there to make sure each one gets the chance to do damage control.
* Logging level could be set by a global configuration flag which defaults to `INFO`

**Comment by rizar** [comment]
> logger.error calls currently result in mysterious no handler found errors with no further information to > the user; we either need to use logging.error() or call logging.basicConfig() 

We should put something like this in `MainLoop.run`:
```python
if not logging.getLogger().handlers:
    logging.basicConfig()
```

> Right now the first SIGINT just tries to finish the batch, but the second one quits halfway the batch 
> and then tries to run the after_training extensions, which could screw things up more than it could fix.

Are you sure? The second one should now be handled as any other exception because of
```python
if not self.log.current_row.got_exception:
    self._run_extensions('after_training')
```

> The on_interrupt callback isn't used so far, and maybe we should remove it until a good use case 
> comes along?

It is used in `Printing` extension, though it can be discussed if it should be used.


Your suggestions are good. I would use global configuration for logging only if the user has not called `basicConfig` himself.

**Comment by bartvm** [comment]
`logging.basicConfig()` does nothing if there are already stream handlers for the root logger, so you can safely call it without performing any check. It was made for exactly that.

`KeyboardInterrupt` and `SystemExit` don't inherit from `Exception` and won't be caught by the current code, so the `after_training` extensions would be run either way. We would need to deal with `KeyboadInterrupt` separately (i.e. not use a bare `except:` statement) because we probably don't want to catch `SystemExit`.

I really need to stop using GitHub's search function, because it doesn't show `Printing` when searching for `on_interrupt`... Happy to leave it in then.

**Comment by rizar** [comment]
```grep 'something' -R --include '*.py' .``` !!!

**Comment by bartvm** [comment]
I prefer `ack --python 'something'`, but yeah, it's clear that GitHub search isn't a replacement for the command line :)
