### ISSUE TITLE
Serialization Does not Work for Python 3.3

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#293]
Error message below. From my quick look into it seems like somebody's relying of range iterators. 

```
======================================================================
ERROR: tests.test_examples.FunctionTestCase (test_mnist)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rizar/Dist/blocks/tests/__init__.py", line 19, in wrapper
    test(*args, **kwargs)
  File "/home/rizar/Dist/blocks/tests/test_examples.py", line 31, in test_mnist
    main_loop = dill.load(source)
  File "/usr/local/lib/python3.3/dist-packages/dill/dill.py", line 199, in load
    obj = pik.load()
  File "/usr/lib/python3.3/pickle.py", line 840, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.3/pickle.py", line 1246, in load_build
    setstate(state)
ValueError: index out of range
```

**Comment by bartvm** [comment]
Do we really need to tag this with *major*? Supporting every outdated Python version will be a nightmare!

For anyone who wants to go bug hunting, these cases seem to have the same error: https://github.com/pydata/pandas/issues/6871, https://github.com/quantopian/zipline/issues/475 and https://github.com/uqfoundation/dill/issues/27

**Comment by rizar** [comment]
I tagged this major because it is not too old of a Python and comes with my Ubuntu 13.10 - not too old of an Ubuntu. So I thought that this is a version supported by Blocks. But if we decide that we do not support anything earlier than 2.7 and 3.4, then this tag is too much, agreed.

**Comment by bartvm** [comment]
I'm closing this one because we're not longer using dill, but let me know if it happens with `cPickle` as well!

**Comment by saitam1** [comment]
Was this fixed?
I get an error on running `perf = pd.read_pickle('buyapple.pickle')`

Error:
`IndexError: tuple index out of range`
