### ISSUE TITLE
There is no variable for sequence generator in computational graph when `iterate=True`

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [bartvm/blocks#305]
Hi, I'm trying to experiment with `test_integer_sequence_generator` and it seems, that the graph 
```python
states, outputs, costs = generator.generate(
        iterate=True, batch_size=batch_size, n_steps=n_steps)
cg = ComputationGraph(states + outputs + costs)
```
doesn't contain variables for `readout.emit` application. When the graph
```python
states, outputs, costs = generator.generate(
        iterate=False, batch_size=batch_size, n_steps=1)
cg1 = ComputationGraph(states + outputs + costs)
```
does contain. What is the reason for it?

**Comment by rizar** [comment]
This is a natural consequence on the way scan is implemented in Theano.

In the first case `readout.emit` is only used within the scan inner function, the one which is passed a the first argument to `theano.scan`. In the second case `theano.scan` is not called, instead the inner graph of the scan used in the first case is returned. In this graph there is a reference to `readout.emit`. 

To implement beam search you need the second call, I guess.

**Comment by dmitriy-serdyuk** [comment]
Thanks!

**Comment by rizar** [comment]
You are welcome! By the way there is now a google group for asking questions about Blocks: https://groups.google.com/forum/#!forum/blocks-users. Feel free to ask any question there!
