### ISSUE TITLE
Reverse Words Demo Is not Resumable

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#313]
Due to a Theano bug, I can not unpickle the algorithm.

Created an issue https://github.com/Theano/Theano/issues/2516

**Comment by rizar** [comment]
It struck me just now that we are having the same problem in Blocks.

Singletons, pickling and `==` comparison are just incompatible. Because an unpickled singleton is already another object. Should we override `__eq__` for all roles so that it checked type equality, not object equality?

**Comment by bartvm** [comment]
That sounds reasonable.

**Comment by rizar** [comment]
The bug in Theano was fixed.
