### ISSUE TITLE
Fuel

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#332]
Before we diverge much further, it would be nice if we switch to Fuel. It should be a very simple renaming task.

**Comment by rizar** [comment]
There is one thing that I do not understand about the Fuel project: will it contain all sorts of dataset or only the core functionality to implement those? How is it related to the planned `blocks-contrib` repo?

**Comment by bartvm** [comment]
Although not containing every possible dataset, I think a lot of people appreciate there to be wrappers for the more important datasets. Now that Fuel has been factored out of Blocks, I have less of a problem with that. It's a data framework after all (unlike Blocks, where I think it would have unnecessarily bloated the codebase given its core functionality as a Theano framework).

I imagine `blocks-contrib` to still be for examples, reproductions of papers/classical experiments, etc. I'd actually suggest also moving some extensions there. Some extensions can be useful, but just aren't used enough to be worth the effort the effort to maintain as part of the core on the long-term. Separating them out means that if they ever break, the core doesn't break, which could really stifle development.
