### ISSUE TITLE
mlp has no attribute 'get_objective'

### ISSUE THREAD

**Issue by fvisin** [bartvm/blocks#334]
Following the [first tutorial](http://blocks.readthedocs.org/en/latest/tutorial.html#the-task) I get the following error when I run the model.
Apparently the mlp object doesn't have the get_objective() method implemented.
I did not dig very much into it, let me know if the error is straightforward for you to understand, otherwise I will look into the code and see what I can find.

```
main_loop.run()
  File "/home/francesco/exp/blocks/blocks/main_loop.py", line 137, in run
    if not self._model.get_objective() == self.algorithm.cost:
AttributeError: 'TensorVariable' object has no attribute 'get_objective'
```

**Comment by rizar** [comment]
This a too enthusiastic sanity check with should not have run! I will fix it in a minute.

**Comment by rizar** [comment]
I changed my mind: this tutorial does not need a model at all.

**Comment by bartvm** [comment]
We should probably call the run method without the Printing extension as a
hidden doctest to make sure that we don't break the tutorial again.
