### ISSUE TITLE
Filtering by Application does not Work after Unpickling

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#340]
Need to think more what happens here, but looks like it is yet another issue with singletons and pickling: the `Application` objects are singletons.

**Comment by bartvm** [comment]
Should be easy to fix by implementing `__eq__` to check whether the owning brick classes are the same, right?

**Comment by rizar** [comment]
... and that the names are the same. Seems like that. Could be a CCW ticket for somebody who can is able to read `blocks/bricks/base.py`.

**Comment by rizar** [comment]
So I have done some research and removed CCW label :)

The summary of the issue: the link between bricks and bound applications are lost after pickling and unpickling _in a new process_. This happens because new `Application` objects are created, with empty `bound_applications` dictionaries. So `brick.apply` results into a creation of a new `BoundApplication`.

A solution idea: the links to the `BoundApplication` should be stored in the bricks, not in the applications. I will try to implement this.
