### ISSUE TITLE
Ability to restrict application of a StepRule to a subset of parameter tensors

### ISSUE THREAD

**Issue by dwf** [bartvm/blocks#353]
I brought up in the comments on #352 that it would be useful to be able to restrict the application of a `StepRule` to only certain parameters.

A useful trick with convolutional nets is to scale the steepest descent/momentum by some factor for the convolution parameters only. Also, clipping the norm of only the update to the recurrent weights seems like a sane thing to do (if it's not currently what's done in the literature; I thought it was).

Quoth @bartvm:
> Yeah, that does sound reasonable. Not sure what the best way of implementing it is. I guess there are two ways: Either we give all step rules automatic support for e.g. exclude or filter keyword arguments, which makes them pass on excluded parameters/all parameters that don't match the filter without changing them.

> The other way would be to create a a FilterStep which works like `step_rule=FilterStep(StepClipping(threshold=100), VariableFilter(roles=[RECURRENT_WEIGHTS])(cg.shared_variables))`. I guess this could be more powerful because you could easily filter weights for an entire sequence by doing something crazy like `step_rule=FilterStep(CompositeRule(...), VariableFilter(roles=[BIASES])(cg.shared_variables))`.

@rizar was the main architect of the current iteration of `StepRules` so it'd be good to have his input before taking any action.

**Comment by rizar** [comment]
I like this idea and it also seems like a good showcase for advantages of having an annotated computation graph!
The most modular way to do it is a step rule wrapper like the `FilterStep` as @bartvm proposed. My only input will be a suggestion to call it `Restrict`, which would be very easy to read: application of a certain rule is restricted to the following parameters:

```python
CompositeRule([StepClipping(100),
                             Restrict(RemoveNotFinite(0.1), VarilableFilter(...)(cg)),
                             Adadelta()])
```
