### ISSUE TITLE
Rename SerializeMainLoop to Checkpoint

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#361]
Now that we're still giving ourselves the leeway of refactoring at will without versioning, I'd like to propose renaming the rather lengthy and obscure `SerializeMainLoop` to `Checkpoint`. This is what we call it after all, and you don't need to be familiar with the terms "main loop" and "serialisation" to know what it does.

**Comment by rizar** [comment]
Fine with me!

**Comment by bartvm** [comment]
Fixed in #452
