### ISSUE TITLE
data_path value should go to ~/.fuelrc

### ISSUE THREAD

**Issue by EderSantana** [bartvm/blocks#369]
I tried to run the MNIST tutorial from the docs and got the Configuration Error. The same docs mention to add a data_path value to ~/.blocksrc. But this doesn't work, data_path should actualy be at your ~/.fuelrc and that is not mentioned on the docs. You can only realize that reading Fuel's source.

**Comment by bartvm** [comment]
Oops, that slipped the net when switching to the new Fuel backend. I'll change it in a bit.

**Comment by bartvm** [comment]
#370 should fix it, I'll just wait to see what the tests say before merging.

**Comment by rbharath** [comment]
The current version of the tutorial (see http://blocks.readthedocs.org/en/latest/tutorial.html) doesn't seem to mention the need to set ~/.fuelrc. I ran into the same problem as @EderSantana when running the tutorial.
