### ISSUE TITLE
Various VariableFilter Inteface Improvements

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#391]
Should only be done after #165 

- accept a single brick, not only list

- accept a list of bound applications, not only a single one

- rename `name` argument to `name_re` and introduce a new `name` which corresponds to exact matching instead of matching with a regular expressions

- add `one` keyword argument. If `one=True`, either return the found variable, or `None`, or raise an exception if several were found

**Comment by rizar** [comment]
@bartvm, does the  `CCW` label mean that the issue is suitable for the CCW format or that the decision has been taken to do it in `CCW` hours?

**Comment by bartvm** [comment]
That it's suitable. It adds the ticket to the CCW system so that we can
assign it to people.

We'll need a few CCW tickets for this week by the way!

**Comment by dwf** [comment]
@mducoffe This one's for you this week!

**Comment by jbornschein** [comment]
Maybe we should also have the option to filter recursively a given brick and it's children (instead of only returning variables that directly belong to a certain brick).

I was missing this feature when I wanted to find all parameters in a given brick which could potentially contain a MLP (or not).

**Comment by bartvm** [comment]
Does `Selector(brick).get_parameters().values()` not suffice? That should give you all the parameters of `brick` as well as its children.

**Comment by jbornschein** [comment]
Doh, I missed the complete selector interface! That should do it, Thanks!
