### ISSUE TITLE
Feedbacker -> feedback brick?

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#396]
Some of the code in `sequence_generator.py` uses "feedbacker" to refer to the brick that is supposed to provide feedback to the generator. The word "feedbacker" seems a bit contrived, and I was wondering if we can't just change it to "feedback" or else "feedback brick"?

**Comment by rizar** [comment]
Yep, we can change it to `Feedback`, but only after changing the name of its application method to `apply` to avoid confusion.

**Comment by rizar** [comment]
I was just trying to refactor it, and ran into difficulties: the `Readout` brick ends up having up an attribute `feedback` and an application method `feedback`. Do you see a way for this linguistic trap?

**Comment by bartvm** [comment]
`feedback_brick`?
