### ISSUE TITLE
N-D Adapter for 2-D only bricks.

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#401]
A brick that would wrap another brick by flattening inputs before application of the wrapped and converting the output back to the original shape. If we had this, I could significantly refactor the `SoftmaxEmitter` from `blocks/sequence_generators.py`.

**Comment by rizar** [comment]
@vdumoulin , at some point you wanted to implement such a thing, as far as I remember.

**Comment by bartvm** [comment]
This is basically the same as #101 I believe, so I'll close that one.

**Comment by rizar** [comment]
Right, forgot about that one, sorry!

**Comment by vdumoulin** [comment]
Right, I can do that in the next couple days if you'd like.

**Comment by rizar** [comment]
Okay, when you have time.

**Comment by vdumoulin** [comment]
@rizar see #404

**Comment by vdumoulin** [comment]
If you also need to wrap an application call with `dimshuffle` calls, I can also implement a `WithAxesSwapped` brick in the same kind of fashion.

**Comment by rizar** [comment]
Closed by #404

**Comment by dwf** [comment]
Strangely it didn't actually close.
