### ISSUE TITLE
[doc] clarify intended use of the StepRule "updates" list

### ISSUE THREAD

**Issue by dwf** [bartvm/blocks#424]
I presume that this is for e.g. updating Markov chains in some sort of MCMC-based gradient estimator, it would be good to document this though. @rizar Can you confirm that that's the sort of intended use case you had in mind?

**Comment by rizar** [comment]
Do you mean the updates returned by step rules? Those are needed to implement various accumulations like momentum. I guess you mean something else, but do not see what.

**Comment by dwf** [comment]
Ah, of course. (When doing e.g. RBM training with persistent contrastive divergence, one needs to update the persistent Markov chains on every step, which this could also be used for, potentially.)
