### ISSUE TITLE
SequenceGenerator's cost method returns cost matrix

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#434]
Just wondering if we should make it behave similar to the cost bricks instead. That is, the current `cost` method should really be called `cost_matrix` and `cost` should instead be the average cost per sequence element
```python
def cost(...):
    cost = self.cost_matrix(...) / mask.sum()
    cost = add_role(cost, COST)
    return cost
```

**Comment by rizar** [comment]
Agreed, There is even no need in `cost_matrix`, because it can be added to the computation graph as an AUXILIARY variables.

I should say that AUXILIARY variables are an ultimate tool and make code both clear and possible to debug!

**Comment by bartvm** [comment]
That's also an option, but I wouldn't mind having it as a separate application either, since that's more consistent with the interface the cost bricks have.

**Comment by dwf** [comment]
@orhanf This one's for you. Let me know if you have any questions.

**Comment by bartvm** [comment]
Just talked about this with @orhanf and @sebastien-j, and we actually want two costs:

If you monitor during training, you would want your costs to be comparable. That means averaging the cost to cost-per-token i.e. `(probs * mask).sum() / mask.sum()`. However, for training, this would make batches with fewer numbers of tokens weigh heavier. So for training, you don't want to average at all (because if you average per sentence, you would bias towards particular sentences). The training cost would just be `(probs * mask).sum()` then. This obviously makes it impossible to compare between batch sizes, but it's training cost anyway, so I guess that's okay.

I think we should return `(probs * mask).sum()` by default, but make the other one available as an auxiliary variable.

**Comment by orhanf** [comment]
Okay, I've changed `cost(...)` to `cost_matrix(...)` and added an AUXILIARY variable to `application_call`  for `(probs * mask).sum() / mask.sum()`. But still, I think if we change the method name to `cost_matrix(...)` for consistency, then it should return `(probs * mask)`. Shall I also add `cost(...)` method to return `(probs * mask).sum()` ?

**Comment by bartvm** [comment]
Yeah, `cost_matrix` should return that matrix, while `cost` should probably add the auxiliary variable and return `self.cost_matrix(*args, **kwargs).sum()`
