### ISSUE TITLE
Pickling is insanely slow and space-inefficient

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#442]
My current model refuses to pickle because it says it runs out of space on `/tmp`... Turns out that my `/tmp` is 8GB, while the pickle file ends up being 18GB+!

The main issue seems to be that we're using the default protocol, which is 0 Python 2. This is insanely inefficient. Using protocol 2 takes about 1/10th of the time, and results in a file which is "only" 4.6GB.

**Comment by bartvm** [comment]
As a side note: It might be worth checking if using joblib gives a significant speedup here. @dwf You used that for Pylearn2, right? Did it work well?

**Comment by rizar** [comment]
The current log implementation is also very far from ideal. We have a Python object for each record, which is huge waste of resources.

I see two possible solutions: 

- a new log class that uses Pandas as a backend. Such a log class would have to move all its data once in a while, because there is no efficient way to append to Pandas structure. The only solution I know is to increase the storage size twice whenf it runs out. 

- a new log class that uses a database as a backend, e.g. `sqlite`. Might be quite nice to have it, @janchorowski wanted this at some point. A cool thing would be that data is loaded on request, not all at once.

**Comment by bartvm** [comment]
Sqlite and pandas don't make much sense to me because of the structure we
have for the log, where the number of keys can be different for each step.

A key-value NoSQL database like Redis or CouchDB is probably better suited.

**Comment by bartvm** [comment]
All of these solutions make it impossible to log arbitrary python objects though, which I think is a big disadvantage (although a key-value database should at least allow for lists and dicts easily).

Although I wouldn't change anything without benchmarking first (good chance the log is negligible compared to the huge parameter sets), maybe a dict of dicts, or a list of integer-dict pairs is a better solution.

**Comment by janchorowski** [comment]
Increasing the size by a constant factor of 2 or 1.5 gives amortized 
O(1) insertion, this is how the list works in Python. For homogenous 
objects the array class might be good, we will skip pointer creation. 
With a DB backend different number of keys per iteration is not such a 
great problem, you store (iter, key, value) triples in the db. However, 
as @bartvm points out, arbitrary python objects will need to be pickled 
and stored as blobs.

**Comment by bartvm** [comment]
If you need to start implementing your own memory management, you've picked the wrong tool for the job IMHO. Pandas is awesome, but it's not made to deal with steaming data with a variable number of keys.

Sqlite could work, but I'd be worried about performance if we need to pickle every python object, especially if the user wants to store large NumPy arrays (e.g. if I want to log gradients or Hessians).

I would just stick with Python as the primary implementation, maybe sqlite as an optional secondary one. If the large number of objects is actually a problem (I'm not sure it is, really need to benchmark that!) we can manage that within Python by either switching to a list/dict of dicts as I suggested, or by using `__slots__` to make these objects lighter weight.

**Comment by bartvm** [comment]
CC @lamblin @dwf  I'm just reopening this because I think it warrants a bit more investigation. My search as brought me this far: Theano seems to be the main culprit. Of a 11GB file, 10GB is from the `algorithm` attribute where the parameters and computation graph are stored. Using [this pkldu script](http://hg.assembla.com/pylearn/file/88f361283a19/bin/pkldu.py) with some adaptations, I get the following (a lot of the other attributes fail to pickle though, so e.g. `_updates` is missing here but it should be at least as big as `steps`):
```
field: _cost_computation_graph                  1274350118.00  B ( loads in   8.46 s)
field: cost                                     1274340097.00  B ( loads in   3.23 s)
field: gradients                                4424024620.00  B ( loads in  20.72 s)
field: params                                   409319605.00  B ( loads in   0.10 s)
field: steps                                    7862273808.00  B ( loads in  48.21 s)
``` 
The bizarre thing here is that dumping `[param.get_value() for param in main_loop.algorithm.params]` results in a file of 167MB, while dumping `main_loop.algorithm.params` results in 391MB. The second bizarre thing is clearly that the gradients take over 4GB. If the parameters are only 400MB, what is the other 3.6GB?

**Comment by bartvm** [comment]
Okay, so after a bit more investigation, it seems to have to do with the annotations we add to variables, because normal Theano variables don't have this problem. My guess is that somehow pickle chokes completely on the web of dependencies that our annotations create.

**Comment by bartvm** [comment]
Found it! Hurrah! Something very silly in the end: I was using `test_value` somewhere. Theano happily serializes this, so I was quite literally pickling NumPy arrays for every single intermediate result in the entire graph. My pickle file just went from 11GB to 520MB.

@lamblin @nouiz Would it be an option to skip `test_value`s when pickling Theano variables? Or maybe print a warning at least? It's a bit of a nasty thing to track down, and it never occurred to me.
