### ISSUE TITLE
get_dims should return OrderedDict

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#453]
That makes it easier to do things like `input_dims = brick.get_dims(input_names).values()`

**Comment by dwf** [comment]
There's a `get_dims`?

**Comment by dwf** [comment]
Nevermind, looking in wrong file.

**Comment by bartvm** [comment]
Actually, I think `get_dims(input_names)` should return a list. If the user wants a dictionary he can just do `zip(input_names, get_dims(input_names)`. I'm actually making a PR now where I replace al lot of dictionaries (mostly in `parallel.py`) with lists.

I'm starting to really dislike having these dictionaries of dimensions all over the place. It's very redundant and, because of that, dangerous. A user can change the name of an input source of a brick, but that won't be reflected in all of the dictionaries, resulting in strange errors. Having to use custom-written `dict_union` everywhere is annoying as well, instead of just being able to concatenate two lists (or use `extend`).

It is less flexible of course, because the user needs to make sure that the list of dimensions and source names match up, but the added safety justifies the occasional `self.dims[self.input_names.index(name)] = 5` instead of `self.dims[name] = 5` IMHO.

**Comment by rizar** [comment]
This change would add a potential source of errors: for every list of dimensions the user has to know the respective list of names, and if there are several list of names, he can choose a wrong one.

But altogether I am fine with this change.
