### ISSUE TITLE
Make the Log Behave in a More Standard Way

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#460]
Current the `TrainingLogRow` returns `None` for any attribute request. While it is convenient in certain cases, it's quite a deviation from what a Python object typically does. When I tried to add similar logic to `TrainingStatus` that caused pickling error because request for the `__setstate__` method was handled incorrectly. I don't know why it does not happen to `TrainingLogRow` as well.

So I think we should switch to more Pythonic behavior and raise an `AttributeError`. To avoid doing 
`if hasattr(log.current_row, 'record') and log.current_row.record == True` all the time, we should provide `get` method similar to `get.dict` and use upper-cased constants for multiply used record names, such `training_finish_requested`.

**Comment by rizar** [comment]
Just remembered that there is `getattr(log.current_row, 'record', False) == True`, which leaves the question whether we need `get` method open.

**Comment by bartvm** [comment]
Part of the discussion at https://github.com/bartvm/blocks/pull/476

**Comment by rizar** [comment]
Fixed by #541
