### ISSUE TITLE
Unexpected behaviour of `recurrent`

### ISSUE THREAD

**Issue by laurent-dinh** [bartvm/blocks#479]
I made a gist [here](https://gist.github.com/laurent-dinh/648b948532f36d4c9dbb).
The outputs of `apply` follow the same order as the `outputs` argument of `recurrent` but it does not seem to work well...
I've put a breakpoint in recurrent (around [that area](https://github.com/bartvm/blocks/blob/master/blocks/bricks/recurrent.py#L186-L190)) and I find it strange that `args` has length 2 where as it should take `sequences` + `outputs_info` + `non_sequences` afaik (given the `scan` documentation). However if I go back [`list(sequences_given.values())`](https://github.com/bartvm/blocks/blob/master/blocks/bricks/recurrent.py#L203) has length 1 and [`outputs_info`](https://github.com/bartvm/blocks/blob/master/blocks/bricks/recurrent.py#L204) has length 2, also [`outputs`](https://github.com/bartvm/blocks/blob/master/blocks/bricks/recurrent.py#L191) has length 2.

**Comment by rizar** [comment]
I have a bad feeling about this: `outputs=['outputs', 'states']`. As far as I remember it is hardcode somewhere in `recurrent.py` that states go first in the outputs list. Can you try to replace them and tell me what happens?

**Comment by rizar** [comment]
I checked, that helped.

If you wish, you can modify the tutorial to mention that. Also it should be a part of the `recurrent` decorator docs.

**Comment by bartvm** [comment]
Just wondering whether you reopened intentionally or accidentally?

**Comment by rizar** [comment]
Intentionally: this should stay open until changes in the docs are not made. This is a pretty crucial shortcoming of the documentation.

**Comment by rizar** [comment]
The "states goes first" requirement is effectively lifted by https://github.com/bartvm/blocks/pull/498/files
