### ISSUE TITLE
Doubts about GatedRecurrent class

### ISSUE THREAD

**Issue by EderSantana** [bartvm/blocks#492]
The GRU apply method got this:
```python
if (self.use_update_gate != (update_inputs is not None)) or \
(self.use_reset_gate != (reset_inputs is not None)):
raise ValueError("Configuration and input mismatch: You should "
"provide inputs for gates if and only if the "
"gates are on.")
```
Wouldn't it be better to use the default input to gates (data and previous states as in the paper) if the user already defined that he wants to use the gates? I got the idea that this way the user can get an MLP for the input_to_{reset,update}. In that case its better to ask for the actual activations (what if I want an MLP for state_to_reset as well?).

In that case, I suggest the following __init__ signature:
```python
GatedRecurrent(activation, dim, use_reset=True, use_update, input_to_update=Sigmoid(),   
state_to_update=Sigmoid(), input_to_reset=Sigmoid(), state_to_reset=Sigmoid())
```

Or make a super class that is fully customizable and make GatedRecurrent as specific case (i.e. following Sigmoid() and {input,statate}_to_{reset,update} like in the paper. The fully customizable thing could probably get both GRUs and LSTMs as specific architectures...

What if I want a [GRU as gating function of GRU](http://media.tumblr.com/tumblr_ltuzjvbQ6L1qzgpx9.gif):

Anyways, it is just really sad that GatedRecurrent right now is not as easy to use as SimpleRecurrent. Its is also important to note that for general usage, it would be nice to get the most used bricks consistent with the simple API of MLP. Asking for extra stuff at `apply` as default just makes GatedRecurrent inconsistent with MLP.

Whatever you prefer, I can work on it if you want so.

**Comment by bartvm** [comment]
I'm not sure I fully understand what you are suggesting. I guess that the current design decision was just based on the paper, which assumes separate weight matrices *W*, *W_r* and *W_u*. However, the current `GatedRecurrent` does *not* perform these 3 transformations (because they are not part of the recurrence relation). Hence you're expected to give three inputs, which most of the time will be something like *W.x*, *W_r.x* and *W_u.x*. If you want to use an MLP to calculate e.g. the reset gate you would simply do something like `reset_inputs=mlp.apply(x)`, which should work fine. Likewise, if you want to use a GRU to calculate the reset inputs to a GRU, `reset_inputs=gated_recurrent.apply(x)` should work too.

Anyway, I'll let @rizar comment on why he settled on the current interface.

**Comment by EderSantana** [comment]
That's my point. `W, W_r, W_u` ARE part of the recurrence relation. The input `x` is already there as well... I'm just suggesting that `GatedRecurrent` should provide default values for all of them.

**Comment by bartvm** [comment]
They're not, in the sense that given an input `x` you can calculate `W.x` for each time step without needing any sort of recurrence. This is why we keep it outside of the brick; calculating it inside the brick means calculating it inside `theano.scan`, which is far, far slower than doing it outside.

If you want to have `recurrent_inputs=Linear().apply(inputs)` as a default (not sure if this is what you are suggesting?), it would make the brick a lot messier to write. As I mentioned, for performance reasons you would have to make sure that the linear transformation happens outside of `theano.scan`, so you would need two bricks (one to perform the default transformations if necessary, wrapping a second brick which calculates the recurrence).

Have you looked at the `Fork` brick? It is very handy in these cases. For example, if you have a 500-dimensional input and a 1000-dimensional state, you can easily create the `W`, `W_r` and `W_u` matrices with something like `gated_recurrent.apply(**Fork(input_dim=500, output_dims=[1000] * 3, output_names=['inputs', 'reset_inputs', 'update_inputs']).apply(x))`

**Comment by rizar** [comment]
It's hard to add anything to what @bartvm said. You really don't want to compute reset and update inputs inside scan: that's slow. For this reason this is not a part of `GatedRecurrent` but should be done somewhere before. 

Note that `LSTM` brick in fact also gets four inputs, though it expects them concatenated:

```
inputs : :class:`~tensor.TensorVariable`
   The 2 dimensional matrix of inputs in the shape (batch_size,
       features * 4).
```

In fact we could also go this way with `GatedRecurrent`: it makes life a bit simpler and will be useful when doing the optimization requested in #399.

**Comment by EderSantana** [comment]
ow, I didn't know about that speed issue of scan, I can understand that now!! Tkx a lot!!
