### ISSUE TITLE
ComputationGraph.replace doesn't work on graph outputs

### ISSUE THREAD

**Issue by vdumoulin** [bartvm/blocks#515]
The following example fails:
```python
>>> from theano import tensor
>>> from blocks.graph import ComputationGraph
>>> x = tensor.scalar()
>>> y = x + 1
>>> cg = ComputationGraph([y])
>>> doubled_cg = cg.replace([(y, 2 * y)])
>>> doubled_cg.outputs[0].eval({x: 2})
3.0
```

**Comment by rizar** [comment]
@dmitriy-serdyuk , as the author of current `replace` code you might want to take a look.

**Comment by dmitriy-serdyuk** [comment]
Right, outputs are not inputs for any of apply nodes.

**Comment by vdumoulin** [comment]
Is it an oversight or is it wanted?

**Comment by dmitriy-serdyuk** [comment]
I thought about it before, but forgot to add these variables. I fixed it and added a test.
