### ISSUE TITLE
 Base Feedforward Brick

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#52]
Seems like we need a new abstraction: a brick with a single input and a single output that supports setting the input and output dimensions, i.e. has some writeable properties `input_dim` and `output_dim`. Or has `set_input_dim`, `set_output_dim` methods. I suggest an to create an abstract brick `Feedforward` for it.

Motivation: before I used MLPs everywhere for intermediate transformations and configured them with  `mlp.dims[0] = smth`. Now we also have `LinearMaxout` and later we will have `DaisyChain`. There should be a shared configuration interface for all these guys.

Opinions?

**Comment by bartvm** [comment]
Fixed in #184.
