### ISSUE TITLE
Bokeh error - cannot get mnist.py example to run?

### ISSUE THREAD

**Issue by AjayTalati** [bartvm/blocks#532]
HI,

I'd like to run the MNIST example, but I'm getting an error which I think to do with Bokeh?

`simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Here's the error screen.

![bokeh_error_for mnist_example](https://cloud.githubusercontent.com/assets/10279780/6800289/e5b24f5a-d214-11e4-90e2-c7b51f9a8624.png)

Alternatively is it simply possible to run the example without Bokeh ?

Thanks a lot for your help,

Aj

PS - Is there a Google group for Blocks, like `theano-users` and `pylearn-users` ?

**Comment by bartvm** [comment]
Just delete the `Plot` object from the `extensions` argument to `MainLoop` in `mnist.py`, that will stop it from trying to plot things. I'm not sure why Bokeh is crashing in this case I'm afraid...

There's a link to [the mailing list](https://groups.google.com/forum/#!forum/blocks-users) on the front page of the [documentation](http://blocks.readthedocs.org/en/latest/).

**Comment by AjayTalati** [comment]
Great - thanks - I just figured that one myself a minuet ago.

Really nice code :+1:
