### ISSUE TITLE
Possible duplicates in ComputationGraph.variables attribute

### ISSUE THREAD

**Issue by vdumoulin** [bartvm/blocks#533]
This piece of code

```python
from theano import tensor
from blocks.graph import ComputationGraph


x = tensor.matrix('x')
y = tensor.matrix('y')
w = x + y
w.name = 'w'
z = tensor.exp(w)
z.name = 'z'

cg = ComputationGraph([z, w])
print(cg.variables)
print(cg.variables[2] is cg.variables[-1])
```

produces the following output:

```
[x, y, w, z, w]
True
```

Is it desireable behaviour?

**Comment by bartvm** [comment]
Nope, I think it comes from these lines: https://github.com/bartvm/blocks/blob/master/blocks/graph.py#L128-L130

It basically appends all `outputs` to the list, without checking whether any of the outputs already appear in the graph that defines the other outputs. Replacing `+ self.outputs` with `+ [var for var in self.outputs if var not in seen]` should fix it.

**Comment by vdumoulin** [comment]
Ok. I'll make a PR out of it.

**Comment by vdumoulin** [comment]
@bartvm My PR in #534
