### ISSUE TITLE
Initialize weights with a numpy array or a shared variable

### ISSUE THREAD

**Issue by adbrebs** [bartvm/blocks#535]
If I am not missing anything, it does not seem possible yet to (easily) initialize brick parameters with numpy arrays or shared variables. What would be the best way to implement it?

Creating a class inheriting from NdarrayInitialization could be a solution (but we would have to be careful when a brick has children).  This also means that we would have to change the NdarrayInitialization interface because there would not be any "generation" with this new class.

**Comment by dwf** [comment]
What's wrong with calling `brick.allocate()` and then `brick.W.set_value(...)`?

**Comment by bartvm** [comment]
If you want something fancier, something along the lines of `Selector(top_bricks).get_params()` should give you a dictionary of parameters with sensible names. You can then match these names to whatever files you're trying to load, and just call `set_value` on each corresponding parameter.

I guess that something like `weights_init=Load('layer_2.npy')` could possibly be nice, but it seems mostly convenience/syntactic sugar.

**Comment by adbrebs** [comment]
> What's wrong with calling brick.allocate() and then brick.W.set_value(...)?

it is not very elegant/user friendly as you are doing two operations  (initialization of array to nan + copy of the target array) whereas it can be done in only one (initialization of the array with the target array).

> weights_init=Load('layer_2.npy')

Yes, it it is also my suggestion, I can do a PR if you are all happy with it.

**Comment by rizar** [comment]
> it is not very elegant/user friendly as you are doing two operations (initialization of array to nan + copy of the target array), whereas only one operation is sufficient (initialization of the array with the target array).

I think that this is quite practical though and does not take too much runtime. There should be one and one obvious way to set parameter values explicitly, and this way is `allocate` and `set_value`, I think.

I close the issue, feel free to reopen it if you find it necessary.
