### ISSUE TITLE
ApplicationCall arguments

### ISSUE THREAD

**Issue by dwf** [bartvm/blocks#540]
`ApplicationCall` takes two arguments, an `Application` and a `Brick`. But it sounds like it does not actually need the `Brick` and could just get this from the `.brick` attribute of the `Application`. Is that the case?

**Comment by dwf** [comment]
Also, the documentation doesn't really make it clear why you'd actually want to do this.

**Comment by bartvm** [comment]
`Application` isn't bound to a particular brick instance, but if it's a `BoundApplication` then yeah, it could just get it from the `.brick` attribute.

**Comment by dwf** [comment]
Sorry, yes, it's a `BoundApplication`.
