### ISSUE TITLE
examples.py contains attribute setting of weghts_init

### ISSUE THREAD

**Issue by dwf** [bartvm/blocks#561]
It is unfortunate that static analysis cannot easily catch this.

**Comment by rizar** [comment]
`examples.py` - do we actually have such a file in the repository?

**Comment by dwf** [comment]
Sorry, tired. It's in the reverse words demo.

**Comment by rizar** [comment]
Do you mean https://github.com/bartvm/blocks/blob/master/examples/reverse_words/__init__.py#L167? Why is it bad?

**Comment by dwf** [comment]
https://github.com/bartvm/blocks/blob/master/examples/reverse_words/__init__.py#L170

**Comment by rizar** [comment]
Oh, you mean the typo! Sure, I will fix it right away.
