### ISSUE TITLE
output shape error for Convolutional

### ISSUE THREAD

**Issue by Stan-ST-SUN** [bartvm/blocks#582]
Line 117-119 of briks.conv.py returns wrong output shape, because:

(1,) + numpy.array([2,3]) = numpy.array([3,4])

to fix this:

(1,) + tuple(numpy.array([2,3])) = (1,2,3)

Using Python 2.7.8 in Windows 7.

**Comment by bartvm** [comment]
The output of `ConvOp.getOutputShape` should be a tuple already, not a NumPy array, see the [Theano code](https://github.com/Theano/Theano/blob/2d3fb05a81463fd414251323ef8e77de33fb0b7d/theano/tensor/nnet/conv.py#L268-L271).

If you got a wrong output shape somewhere, it's probably for a different reason...

**Comment by Stan-ST-SUN** [comment]
Thanks very much.

This caused by my theano version=0.6.
