### ISSUE TITLE
problem with "reverse word" example

### ISSUE THREAD

**Issue by EderSantana** [bartvm/blocks#584]
I trained a reverse word model, but I got the following error when I try to test it
```
INFO:examples.reverse_words:Loading the model..
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    main(**vars(args))
  File "/home/eders/python/blocks/examples/reverse_words/__init__.py", line 260, in main
    model.set_param_values(load_parameter_values(save_path))
  File "/home/eders/python/blocks/blocks/dump.py", line 69, in load_parameter_values
    for name, value in source.items()}
AttributeError: 'Model' object has no attribute 'items'
```
any idea of what is going on?

**Comment by bartvm** [comment]
At first sight, the current `reverse_words` code seems simply wrong. The `load_parameter_values` should be used to load a model that was saved using the `Dump` extension (which saves a `.npz` file with parameter values), but it seems to be trying to load a pickled file instead. You can try replacing the `Checkpoint` extension with a `Dump` extension instead.

**Comment by rizar** [comment]
Currently it should be tested with `.npz`. files. Run `blocks-dump` to get  one and pass it as a command line argument.

Original that was written with a limited resources setup in mind, since I had only one GPU available. As soon as https://github.com/Theano/Theano/pull/2339 is in, it should be rewritten to load the model.

**Comment by rizar** [comment]
I think I answered the questions, can I close the issue?

**Comment by scfrank** [comment]
In case anyone else is stuck on this problem: I ran into the same issue and solved it by adding to `reverse_words/__init__.py`:
```
from blocks.dump import load_parameter_values, save_parameter_values # new import
...
main_loop.run()  # current line 254
save_parameter_values(model.get_param_values(), save_path) # new line
```

**Comment by rizar** [comment]
Why would not running `blocks-dump` and using the resulting parameters do the job for you?

**Comment by scfrank** [comment]
It probably would - I just didn't see this thread until after I'd done the above fix.

**Comment by rizar** [comment]
Okay, thanks for feedback anyway! We should fix it to work out of the box.
