### ISSUE TITLE
SequenceGenerator.cost_matrix silently assumes different tensor shape to that provided by fuel

### ISSUE THREAD

**Issue by mjwillson** [bartvm/blocks#593]
See
https://github.com/bartvm/blocks/blob/master/blocks/bricks/sequence_generators.py#L192
"We assume the data has axes (time, batch, features, ...)"

fuel's TextFile followed by the Padding transformation yields each batch in a matrix of shape (batch, time).

Nothing warned me about this, I guess once the ragged array of sequences has been padded into a matrix there's no way to tell that it's been accidentally used the wrong way around.

I think this means that SequenceGenerator is actually working with the transpose of the padded sequence matrix, which makes no sense and means you'll get mysteriously bad results without an obvious explanation.

For now I think I can work around this by transposing the input matrices (features and mask) to SequenceGenerator.cost.

Am I correct here? Is there a definitive convention in blocks / fuel for which axis of a data tensor for a batch of data should be used for the batch index? Again perhaps worth documenting :)

**Comment by rizar** [comment]
> Is there a definitive convention in blocks / fuel for which axis of a data tensor for a batch of data should be used for the batch index?

There is no such ultimate Blocks convention because it would need too much exceptions :) But as far as I know, sequences are expected as (time, batch, features) everywhere. This is the order imposed by the way recurrent networks work.

On the other hand having the batch size first makes more sense during data preprocessing. 

So you can either pass transposed Theano variable to the `cost` method or transpose the data by a `Mapping` transformer. Taking into account that this faces this issue when working with RNNs in Blocks, maybe `Padding` should have a flag to transpose its results to ensure that time goes first.

**Comment by bartvm** [comment]
It should definitely be more clearly documented, but yes, the Fuel convention is examples first and the Blocks RNN convention is time first. The ideal long-term solution for this is that we tag axes with their semantic meaning (`time`, `batch`, `color`, `width`, etc.), which is part of https://github.com/bartvm/fuel/pull/78 but still needs a lot of work in Blocks. With that information available, bricks can automatically raise a warning if an axis isn't what they think it is.

As a short term solution, I'm not sure whether a `transpose` keyword argument is any good. You'd still need to read the docstring to know of its existence, so we might as well add a warning in the docstring to tell people to do `features.T`. That way we don't have to remove the `transpose=True` keyword argument and break people's code later when we have support for axis semantics.

**Comment by mjwillson** [comment]
OK, thanks for clarifying. 

Semantic axes sound great and transpose argument would help for the time being. I think the main thing is just documenting the conventions prominently -- my assumption from the current docs was that blocks and fuel are sister projects whose conventions line up with eachother. It's particularly dangerous when things silently seem to work when hooked up in the seemingly-obvious way, but actually you need a transpose in the middle for it to be correct.

**Comment by mjwillson** [comment]
Actually I just noticed the shape requirements is documented on 'cost', so perhaps the fault is with me here for not realising that won't line up with what I was getting from fuel. Still might be worth a slightly more prominent warning :)

**Comment by rizar** [comment]
I agree with Bart that we do not need the `tranpose` keyword too much. I close the issue since one in fact can with some effort figure out from docs and examples that data from `Padding` should be tranposed before being fed to `SequenceGenerator`.
