### ISSUE TITLE
Name collisions for Selector.get_params()

### ISSUE THREAD

**Issue by vdumoulin** [bartvm/blocks#596]
At the moment, `Selector.get_params()` doesn't raise any warning or error if there are name collisions in the brick hierarchy. For instance:

``` python
>>> from blocks.bricks import Rectifier
>>> from blocks.bricks.conv import ConvolutionalSequence, ConvolutionalActivation
>>> from blocks.initialization import IsotropicGaussian, Constant
>>> from blocks.select import Selector
>>> convnet = ConvolutionalSequence(
...     layers=[
...         ConvolutionalActivation(
...             activation=Rectifier().apply,
...             filter_size=(3, 3),
...             step=(1, 1),
...             num_filters=4),
...         ConvolutionalActivation(
...             activation=Rectifier().apply,
...             filter_size=(3, 3),
...             step=(1, 1),
...             num_filters=4)],
...     num_channels=3,
...     image_size=(8, 8),
...     weights_init=IsotropicGaussian(0.01),
...     biases_init=Constant(0),
...     name='convnet')
>>> convnet.initialize()
>>> print Selector(convnet).get_params()
# OrderedDict([('/convnet/convolutionalactivation/convolutional.W', W),
#('/convnet/convolutionalactivation/convolutional.b', b)])
```
Part of the problem is the code itself: the two `ConvolutionalActivation` bricks haven't been given names upon instantiation, and their default names collide.

However, I don't think silently overwriting values in the params dict is right (I spent quite a bit of time figuring out why my `Model` object had less parameters than what I get by filtering the computation graph's variable by the `PARAMETER` role).

In my opinion, name collisions should raise an error in `Selector`.

**Comment by dwf** [comment]
+1 that sounds mighty annoying.

**Comment by bartvm** [comment]
Duplicate of https://github.com/bartvm/blocks/issues/480

**Comment by vdumoulin** [comment]
My bad, I searched through open issues but somehow overlooked that one. I'll close this issue, but the code snippet I put there would make a good unit test.
