### ISSUE TITLE
cant load model using h5py

### ISSUE THREAD

**Issue by udibr** [bartvm/blocks#609]
I'm using a data stream using H5PYDataset
I try to load the model saved by Checkpoint
and get
    main_loop= pickle.load(f)
    File "h5py/_objects.pyx", line 178, in h5py._objects.ObjectID.__cinit__ (/private/var/folders/xp/5jdpkg910v151dttm62xh0th0000gq/T/pip_build_udi/h5py/h5py/_objects.c:3924)
    TypeError: __cinit__() takes exactly 1 positional argument (0 given)

**Comment by bartvm** [comment]
Could you give the full traceback and/or a snippet that reproduces the error? From that line alone it's really hard to tell what's going on.

**Comment by rizar** [comment]
14 days without further feedback means that apparently this issue can be closed.
