### ISSUE TITLE
most of the API Reference disappeared form blocks.readthedocs.org

### ISSUE THREAD

**Issue by udibr** [bartvm/blocks#621]
It used to be there .... and it is available inside the code itself, it just does not appear on readthedocs

**Comment by bartvm** [comment]
Seems like RTD updated some things and cleared their build environment, which brought a missing dependency to light. Should be fixed with https://github.com/bartvm/blocks/commit/6bfd88778b07c95b6db70abd5dbf22eb83b7cb3f.
