### ISSUE TITLE
Serialization of datasets (and preprocessing)

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#96]
Now that we have an initial version of datasets, the next challenge: Serialization and preprocessing. This is a pretty difficult problem to tackle, so it's worth some thought.

Serialization is difficult because we don't want to pickle the data each time we save the model (e.g. no point in writing the same MNIST to disk time and time again). Not saving the data and loading it from disk when deserializing is the obvious solution, but comes with pitfalls: If the data isn't where it is was originally, the deserialization will fail and our saved model is now useless.

DWF gave this some thought for Pylearn2, so let me quote from his outline of what would be a solution:

> Automatically loading from disk on unpickling causes unpickling failure if the data has moved or if the path doesn’t exist on that machine. Don’t do one as a consequence of the other automatically.

> **Data loading should be overridable.**
> The lowest common denominator for every kind of dataset is to provide a directory path for loading or saving compatible disk representations. The load path should be specifiable via constructor, and alterable by a method call.

> **Data loading should be lazy.**
> To that end, data should be fetched from data on an as-needed basis. [...] In particular, no additional disk access should be triggered by unpickling: this gives the user the opportunity to modify the data load path, if necessary. This prevents a lot of nasty situations where you cannot unpickle something and you don’t have permissions to create the data paths necessary in order to make it unpickle cleanly.

-----

A separate problem, but one quite closely integrated with serialization, is preprocessing. If we want to support automatic preprocessing such as whitening, ZCA, contrast normalization, etc. there are a few things that should be considered:

* Some preprocessing is global (i.e. for whitening we need the dataset mean and variance), but might need to be able to be applied as an out-of-core algorithm for data that doesn't fit into memory.
* For out-of-core datasets we then have two options, depending on the kind of preprocessing performed: We apply the processing batch-wise during iteration, or we save the modified data to disk and then stream from disk again.
* For in-memory datasets, ideally, we should remove the original data from memory and only keep the processed data.
* Ideally all these pre-processing steps should be serializable/reproducible i.e. with only the original data and a pickle file, we should be able to recreate the pre-processed data exactly (this is where the strong link with serialization as discussed above shows up).

To quote from DWF again:

> **Different facilities for in-memory and out-of-memory data; in-code awareness of which you’re dealing with.**
> Whole-dataset preprocessors should be able to know that they are operating on an in-memory dataset, and fail if they don’t know how to do something intelligent with a certain kind of out-of-memory dataset.
> **Keep records of transformations done on data.**
> It should be possible to regenerate preprocessed data from the default loading path and the log of preprocessing operations upon deserialization. Of course generic containers in the spirit of “DenseDesignMatrix” needn’t provide a default loading path, but given a deserialized object, the load -> (optionally) fit preprocessor -> apply preprocessor should be a simple method call away.

:exclamation: However, I think the best point made is at the end of his document:

> **Is it really worth having the in-{Python,YAML} preprocessor facilities?**
> It seems like this is only of any use for relatively small, in-memory datasets. For large datasets (or even small datasets where you value reproducibility, and different machines will give you different ZCA results, for example), we could support it with a script like
> ```
python preprocess.py \
        --config <description-of-preprocessing> \
        --data_output_path <directory> \
        --output_fitted_preprocessor <pickle file>
```
> You could also add arguments for preprocessing from an already fitted preprocessor object, etc. To use a preprocessed dataset you’d then use the corresponding dataset class and override the load path in the constructor. Viewer code could be passed the serialized pickle file to know how to undo transformations and things like that.

It sounds to me like the pre-processing serialization, etc. would be a real nightmare, and I would argue using this approach for all datasets, in-memory or not. So pre-processing basically happens as an entirely separate step through a script that takes particular datasets (NumPy arrays, HDF5, CSV, etc.) and a configuration file describing what preprocessing to apply as an input. As outputs it produces a new dataset as well as a (pickle?) file which describes what preprocessing exactly has been performed, allowing you to reproduce it and/or reverse it.

**Comment by bartvm** [comment]
@rizar @janchorowski Comment away!

**Comment by rizar** [comment]
So let's start with serialization. Suppose I am working with MNIST and have a data processing pipeline with a data stream in the bottom and  a few wrappers on top of it. What I ideally want is simple: I should be able to resume  iteration right in the state it was stopped at after pickling and unpickling. As far as I understand the proposal of DWF in this context means: the actual data loading is postponed to the point when the first batch is requested. This is done in order to make it possible to change the path to the data after unpickling and before loading the data. Did I understand the idea right?

**Comment by bartvm** [comment]
Yes, that's how I understood it. You could make that pretty transparent by making `self.X` and `self.y` properties which check if the data is loaded already, and load it if not the case. We would then overwrite the `__setstate__` to simply delete the data when being pickled. Unpickling would then happen without trying to reload the data. Only when we request the first batch it would try to load the data again, but in the meantime we could have changed the file path.

**Comment by rizar** [comment]
> We would then overwrite the __setstate__ to simply delete the data when being pickled.

Did you mean `__getstate__`?

**Comment by bartvm** [comment]
Oops, yes.

**Comment by rizar** [comment]
Then it sounds like a good idea. It can be entirely hidden from data streams in a dataset's `get_data` methods and in `__getstate__` and `__setstate__` methods of state objects. I am only concerned about names then: `open` does suggest data loading. Perhaps it should be renamed into e.g. `create`.

As for dataset-level preprocessing, having it in done by a separate script sounds like a good choice for the first version of Blocks. We could return this question later though. So far we nicely support "local" preprocessing when a data-independent transformation is applied to every example: this can be done by data stream wrappers.

**Comment by bartvm** [comment]
Just for reference, after a bit of Googling I came across this particular library which might turn out to be useful: [dill](https://github.com/uqfoundation/dill). It can actually pickle file handles, and if you use `fmode=dill.CONTENTS_FMODE` it seems to also save the position in the file for you. Might be very handy for datasets that e.g. read CSV files.

**Comment by rizar** [comment]
It should be quite easy to make a picklable wrapper on top of Python file handle. This wrapper can save only the position in the file: it is the dataset object where the path to the data is stored. I am not sure if we need an additional dependency for that.

**Comment by bartvm** [comment]
In theory it's easy, but looking at the code of `dill`, there might be a few caveats.

But more importantly, I have a more principal argument. Unlike Pylearn2 and Theano, I would really like to encourage using external frameworks whenever possible (given that the external dependencies are relatively stable). Both Pylearn2 and Theano suffer from a huge problem: Lack of manpower. The less code we need to maintain on the long term the better. I think that especially Pylearn2 suffers from this problem, and it resulted in a massively bloated codebase compared to its core functionality.

Installation wise, `dill` consists of 2-3 pure Python files, which means that when installing Blocks through `pip`, it would take a negligible extra second. I think that e.g. Theano's thinking of not wanting to introduce dependencies is very old-fashioned and ignores the fact that Python has a decent package manager nowadays that makes the process entirely transparent for users. If you install a few Node.JS package, now those are dependencies! You can get dozens of dependencies for a single package there. And that's great, because it means that the packages themselves can stay smaller, and IMHO the fewer SLOCs we have, the better.

We could begin with using `dill` (it only takes one line in `setup.py` and `import dill` at the top), and if on the long term it turns out we need to support different features, or things don't exactly work as we want them to, we can always write our own code to replace it instead. But, especially to get things working in the beginning, it might be a good idea to not duplicate what's already been done.

**Comment by rizar** [comment]
Okay, you convinced me that we need to use as much of external code as possible. Manpower is indeed insufficient, people tend to ask for work only when you talk to them in person, after which event they forget about you forever. I think we should try to make companies interested in Blocks: should perhaps bring us better engineers than science folk.
